### ISSUE TITLE
Can't Change PC (EIP) from UC_HOOK_INTR CallBack

### ISSUE THREAD

**Issue by Coldzer0** [unicorn-engine/unicorn#1027]
@aquynh 

i was implementing SEH handling if Crash Happen or int3 executed , etc ...

SEH handling works fine on UC_MEM_READ_UNMAPPED CallBack
i return True from CallBack as Documented so the Execution Continue 
but if i didn't add this line the code Stop Execution and return error "UC_MEM_READ_UNMAPPED"
```
uc_mem_map(uc, address, $1000, UC_PROT_READ);
```
if i add it the Execution continue to EIP i set
so i think i should be able to continue execution without mapping mem to Exception Address

**Comment by cseagle** [comment]
You can't change eip in your hook because Unicorn ignores your change (at least on x64 and mips?). After your hooks are executed, unicorn does the following in cpu-exec.c:
```
#if defined(TARGET_X86_64)
                    if (env->exception_is_int) {
                        // point EIP to the next instruction after INT
                        env->eip = env->exception_next_eip;
                    }
#endif
```
So unicorn overwrites anything you did with eip with the address of the instruction following the int.
Note that I don't think this is appropriate behavior, and it is the cause of at least three outstanding issues

**Comment by apdbg** [comment]
I have the same problem, how to solve it?
