### ISSUE TITLE
[x86_64] incorrect emulation of most VEX instructions in Qemu 2.11 (ok in Qemu 3.1)

### ISSUE THREAD

**Issue by stevielavern** [unicorn-engine/unicorn#1074]
Hi, 

From my recent tests, most of the VEX instructions are currently not correctly handled by unicorn
- issue #1072 concerns **vmovups**
- issue #1073 concerns **vxorps**
- and I have not created issues for them but I can tell that at least **vpxor** and **vzeroupper** as well have problems

These instructions are correctly handled in Qemu 3.1, but not in Qemu 2.x (tested with 2.11).

Is there any plan to update unicorn with Qemu 3.1? That would probably be a better solution than backporting one by one the fix for each problematic instruction.

Thanks

**Comment by aquynh** [comment]
yes, see https://github.com/unicorn-engine/unicorn/pull/1046.

if you can help to review, test & fix that PR, please do.

**Comment by dmarxn** [comment]
There was a problem with 0xC5 prefixed instructions (If I recall correctly, all the AVX instructions that take two operands)
This was fixed with 5bf6d77. Can you test against a current build with C?
You can look at a similar test in tests/regress/x86_vex.c

While porting to QEMU 3.11 could be awesome, if the fix is already here, you can use it :)

**Comment by stevielavern** [comment]
#1072 seems to be fixed (thanks!), but not #1073 (still same issue).

**Comment by aquynh** [comment]
what is wrong with vpxor?

**Comment by aquynh** [comment]
looks like even Qemu **4.1** cannot handle **vpbroadcastb ymm0, xmm0** ?
