### ISSUE TITLE
How to emulate `SVC` `ARM` instruction?

### ISSUE THREAD

**Issue by goodguysoft** [unicorn-engine/unicorn#1137]
I have no idea how to handle this instruction even it is common in Android code.

So, according to this:

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0552a/BABIFJFG.html

`SVC` instruction transfers control to `VTOR + 0x002C`. Because `VTOR` is not accessible in `unicorn`, I expect that it stores the default `0` value.

So, I try to set SVCall vector in following way:

```
uc_mem_map(uc, 0, 1024, uc_prot::UC_PROT_EXEC | uc_prot::UC_PROT_READ);
uint32_t svc_handler_address = ....;
uc_mem_write(uc, 0x002C, &svc_handler_address, 4);
```
This code not simply fails; it even **crashes the application**, at least in debug mode on Windows:

> Exception thrown at 0x0000000076D5C709 (ntdll.dll) in testhost.exe: 0xC0000005: Access violation reading location 0x00000000E37667CC.

Ok, my next attempt is interrupt handling with hook; `SVC` causes software interrupt, doesn't it? Unfortunatelly, `unicorn` never calls `UC_HOOK_INTR` when `SVC` instruction appears. Even more, **application still crashes** on this instruction.

Is crash supposed to be normal `unicorn` reaction on `SVC` command, or there are some way to emulate this instruction successfully?

**P. S.** We can use `UC_HOOK_CODE` to intercept each and every instruction (because generally we don't know when and if we'll find `SVC` in code), disassemble it (we have to check is it `Thumb` or `ARM` mode now and write 2 disassembling functions, one for `Thumb` and one for `ARM`), stop emulation (because we can not modify `PC` in code hook! it is now it works), and start emulation again from address next to `SVC` instruction. **This solution is ugly for performance**: we don't know when `SVC` command will come, so we do this job for each instruction in code.

**Comment by gerph** [comment]
Handling a SWI (SVC in modern nomenclature) is relatively simple with Unicorn.

I'm using the Python bindings, but the C bindings will be just as simple. In my case I'm handling the SWI call in the Python, so it's actually very simple for me.

Set up a hook, as you suggest. In python this is: 
```python
self.emu.hook_add(unicorn.UC_HOOK_INTR, self.hook_intr)
```

This will catch all execptions, so you need to determine which exception has been raised, and handle it appropriately. You can handle this by manipulating the registers directly at the point of execution and returning to the caller. It was not appropriate for my case, and instead of handling it directly, I cause the emulator to stop and remember the exception that is being invoked:

```python
    def hook_intr(self, uc, intno, data):
        """
        Interrupt or system call (the system entry points)
        """
        self.exit_reason = ('exception', intno)
        self.emu.emu_stop()
```

My emulation code sits within a loop, which will continue the emulator and then decide why it's stopped...

```python
            while True:
                self.exit_reason = ('none',)
                self.emu.emu_start(self.regs.pc, 0x30)
```

At this point, I've determined I can check what the exit reason was. If there was no reason for the exit (`none`) it must have hit the termination address (which I put as address 0x30 - because I don't care about that; I just want it to keep running most of the time). If you set a timeout, then that might also be a reason for the termination and in that case the exit reason will also by `none`.

However, if there is an exit reason set to `exception`, then we've got to go and do some stuff. The exception triggered was in the `intno` field, which is held in the exit_reason, so we use that to decide what to do. In my python this looks something like this:

```python
                if exit_reason[0] == 'exception':
                    if self.debug_execute:
                        print("Exception vector %i called" % (exit_reason[1],))

                    intno = exit_reason[1]
                    if self.debug_swi:
                        print("Interrupt %i" % (intno,))
                    if intno == 2:
                        # SWI call.
                        pc = self.regs[15] - 4
                        if self.debug_swi:
                            print("SWI at &%08x" % (pc,))
                        value = self.memory.read_word(pc)
                        if self.debug_swi:
                            print("Value = &%08x" % (value,))
                            self.regs.dump()
                        swi = value & 0x00FFFFFF
```

At which point I can work out what to do about it - I actually call the kernel's SWI dispatcher, which I've implemented in Python. In most non-semi-hosting cases (eg, when you're going to actually emulate what the system would do), you'd instead call the SWI vector directly... To do that, you'd follow the instructions in the ARM ARM - remember the `CPSR`, remember the `PC`, switch to SVC mode (which will also change `sp` to `sp_svc`), store the `CSPR` in `SPSR`, store the old `PC` + 4 in `LR`, and then set `PC` to the SWI vector entry point (either address 8 or &FFFF0008 depending on whether high vectors are enabled or not). I think that what you were saying was that you didn't know whether the system had enabled high vectors or not. Meh, you probably know what the system is you're emulating, so just use the right one. Or update Unicorn to expose that through a virtual register you can read (I remember seeing it whilst I was looking, but I'm sorry I can't give you pointers at the moment as I don't remember _where_ I saw it).

In my python, I've got a routine that does this, but it's not used in my code...

```python
    def swi_exception(self):
        """
        Actual SWI exception entry, set up just before we call the
        exception handlers + 8.

        Not currently used.
        """
        self.regs.spsr = self.regs.cpsr
        old_pc = self.regs[15]
        self.regs.cpsr = (self.regs.cpsr & ~Registers.MODE_MASK) | Registers.MODE_SVC
        self.regs[14] = old_pc + 4
```

As you suggest, doing the hook for each instruction is a very slow process, and (in my experience) is only suitable for use with tracing. Attempting to subvert execution or change the state of the system within the code hook has not been too successful for me, and if you look at how those hooks are implemented you may see why (as I recall, when the code hook is enabled, every instruction compiled within the JIT has an instruction hook call tacked on to the end of it, and then a check whether it should cause termination of execution or not).

For me - as I'm implementing the system calls mostly in Python - the system I use is pretty good, because it means that I return back to the Python code that did the request for execution and just loop around until some reason causes me to exit (usually a thrown exception in the python code to request termination).

Additionally, this mechanism handles data abort and prefetch abort in exactly the same way as a SWI.

```python
        self.emu.hook_add(unicorn.UC_HOOK_MEM_READ_UNMAPPED |
                          unicorn.UC_HOOK_MEM_WRITE_UNMAPPED |
                          unicorn.UC_HOOK_MEM_FETCH_UNMAPPED, self.hook_unmapped, begin=0, end=0xFFFFFFFF)
```
sets up hooks to trap the faults, and then the hook for those faults decides how it should be handled:

```python
    def hook_unmapped(self, uc, access, address, size, value, data):
        if self.mmios.unmapped_access(address, size, read=(access!=unicorn_const.UC_MEM_WRITE_UNMAPPED)):
            # If it was handled, allow it to continue execution
            return 1

        access_name = 'unknown'
        reason = None
        if access == unicorn_const.UC_MEM_READ_UNMAPPED:
            reason = 'dataabort'
            access_name = 'data_abort_read'
        elif access == unicorn_const.UC_MEM_WRITE_UNMAPPED:
            reason = 'dataabort'
            access_name = 'data_abort_write'
        elif access == unicorn_const.UC_MEM_FETCH_UNMAPPED:
            reason = 'prefetchabort'
            access_name = 'prefetch_abort'

        print("Unmapped memory access type %s (%s)" % (access, access_name))
        print("Address = &%08x, Size = %i" % (address, size))
        print("Value = &%08x" % (value,))
        self.exit_reason = (reason, access_name, address, size, value)
        self.emu.emu_stop()
        # Do not continue
        return 0
```
This uses the same termination trick as the SWI, but with different reason codes. Memory Mapped IO access is handled here too, through the disgusting hack that I describe in https://github.com/unicorn-engine/unicorn/issues/1101 as there is no way currently to handle memory mapped IO within the Unicorn system.

The loop which handles the `emu_start` call is extended to provide handling of the error cases by dispatching to the Kernel's handlers for those aborts (in my Python code). If you were actually providing part of the OS's execution, the handling for those exception entry points is actually near identical to the SWI case, although there are a few registers you might need to set up which might not be directly available in the exposed Unicorn registers (I think the abort address and type registers for where it failed, whether in translation or whatever) - I'm not dealing with that, but in that case you would probably either update Unicorn to expose them, or interpose a small chunk of ARM code that writes to those registers, and then returns to your code so that you can then call the appropriate exception vector.

**Comment by goodguysoft** [comment]
Yes, that's all sound easy, but... **it doesn't work**, at least with Visual C++ 2019. 

See very simple C++ code:

```
#include <cstdint>
#include <iostream>

#include <unicorn/unicorn.h>

void hook_intr(uc_engine *uc, uint32_t intno, void* user_data)
{
	std::cout << "Interrupt occurred!\r\n";
}

int main()
{
	// Create emulator
	uc_engine *uc;
	uc_open(uc_arch::UC_ARCH_ARM, static_cast<uc_mode>(uc_mode::UC_MODE_ARM | uc_mode::UC_MODE_LITTLE_ENDIAN), &uc);
	// Set interrupt filter
	uc_hook interrupt_hook;
	uc_hook_add(uc, &interrupt_hook, uc_hook_type::UC_HOOK_INTR, hook_intr, nullptr, 0, (std::numeric_limits<uint64_t>::max)());
	// Run interrupt
	static constexpr const char code[] = "\x00\x00\x00\xef"; // SVC 0
	static constexpr const size_t code_size = sizeof(code) - 1;
	auto code_segment = _aligned_malloc(1024, 4096);
	uc_mem_map(uc, 0x10000, 1024, UC_PROT_READ | UC_PROT_EXEC);
	memcpy(code_segment, code, code_size);
	uc_emu_start(uc, 0x10000, 0x10004, 0, 1);
	// Unhook
	uc_hook_del(uc, interrupt_hook);
	// Close emulator
	uc_close(uc);
	// Free memory
	_aligned_free(code_segment);
}
```
It **crashes** in debug mode, and it doesn't crash, but also never calls `hook_intr` in release mode.

Is there any workaround? For me, it looks like bug.
