### ISSUE TITLE
how does UC_HOOK_CODE interact with branch delay slots?

### ISSUE THREAD

**Issue by lunixbochs** [unicorn-engine/unicorn#133]
I saw this trace output on MIPS:

```
0x4007e8: 2d009510 beq $a0, $s5, 0x4008a0
0x4007ec: 6a008228 slti $v0, $a0, 0x6a
0x4007ec: 6a008228 slti $v0, $a0, 0x6a
```

This is weird because I got the same instruction address twice in a row (which was confusing the deadlock detection I added to detect bugs in Unicorn). Based on the addresses here, `slti` is in a branch delay slot after the `beq` instruction.

**Comment by xorstream** [comment]
This test case actually jumps to the slti instruction at 400004.
So it executes the slti @ 400004 once due to being in the delay slot, then it executes it a second time during normal execution since it is the target of the branch. So for this test case I would expect to see the slti executed two times.

0x400000: 0000a412 beq    $s5, $a0, 0x400004
0x400004: 6a008228 slti   $v0, $a0, 0x6a
0x400008: 00000000 nop

If instead the test case is changed to the following, then it will only execute the slti once.

0x400000: 0100a412 beq    $s5, $a0, 0x400008
0x400004: 6a008228 slti   $v0, $a0, 0x6a
0x400008: 00000000 nop


So the "fix" that @aquynh did for this should probably be reverted in order to fix issue #290.
HOWEVER reverting that fix leaves the code with a separate issue where the size of the delay slot instruction is 0xf8f8f8f8 instead of 4 (or whatever the real instruction size is, maybe 2 for mips16). Perhaps this is related to the code at "qemu/target-mips/translate.c:19229":
            // save block address to see if we need to patch block size later
            env->uc->block_addr = pc_start;
            gen_uc_tracecode(tcg_ctx, 0xf8f8f8f8, trace->callback, env->uc, pc_start, trace->user_data);

**Comment by aquynh** [comment]
the size of Mips instruction is fixed now, please confirm.

**Comment by xorstream** [comment]
The mips instruiction size fix works.

It still requires a revert or change of the previously altered hook behavior.
I will submit a pull request to fix it.
