### ISSUE TITLE
invalid insntruction: lda.w r0,[r0]

### ISSUE THREAD

**Issue by enoorez** [unicorn-engine/unicorn#1441]
`
uc_engine *uc;
uc_open(UC_ARCH_ARM,UC_MODE_THUMB,&uc);

uc_mem_map(uc,0x10000,0x10000, UC_PROT_ALL);

// d0e8af0f | lda.w r0 , [r0]
uc_mem_write(uc,0x10000,"\xd0\xe8\xaf\x0f",4);

// after call , err = UC_ERR_INSN_INVALID
auto err =uc_emu_start(uc, 0x10000 | 1, 0x10004, 0, 1);
`

**Comment by wtdcode** [comment]
Sry for late reply. Could you provide a full reproduction script?

**Comment by wtdcode** [comment]
Read here: https://github.com/unicorn-engine/unicorn/wiki/FAQ#unicorn-fails-to-emulate-arm-instructions-why

> If so, please use UC_MODE_THUMB and make sure the starting address is odd

**Comment by goodleixiao** [comment]
__main__ | # Tracing PC=0xa0606d28, instruction size=2: 06 90 	 str r0, [sp, #0x18]
   debug_utils | >>> Memory WRITE at 0x101feda0, data size = 4, data value = 0xa, pc: a0606d28
      __main__ | >>Call #0xa0605cc0 - (None, None)
      __main__ | # Tracing PC=0xa0606d2a, instruction size=4: fe f7 ca ef 	 blx #0xa0605cc0
      __main__ | # Tracing PC=0xa0605cc4, instruction size=2: 2b ca 8c e2 	 ldm r2!, {r0, r1, r3, r5}
      __main__ | # Tracing PC=0xa0605cc8, instruction size=4: 2c fe bc e5 	 mcr2 p5, #1, lr, c12, c12, #5
   debug_utils | >>> Memory READ at 0xa0631af4, data size = 4, pc: a0605cc8, data value = 0xa1b812a0
      __main__ | # Tracing PC=0xa012b8a0, instruction size=2: b0 b5 	 push {r4, r5, r7, lr}
   debug_utils | >>> Memory WRITE at 0x101fed78, data size = 4, data value = 0x29d62065, pc: a012b8a0
   debug_utils | >>> Memory WRITE at 0x101fed7c, data size = 4, data value = 0xa0155f25, pc: a012b8a0
   debug_utils | >>> Memory WRITE at 0x101fed80, data size = 4, data value = 0x101fefe8, pc: a012b8a0
   debug_utils | >>> Memory WRITE at 0x101fed84, data size = 4, data value = 0xa0606d2f, pc: a012b8a0
      __main__ | # Tracing PC=0xa012b8a2, instruction size=2: 04 46 	 mov r4, r0
      __main__ | # Tracing PC=0xa012b8a4, instruction size=2: 0d 48 	 ldr r0, [pc, #0x34]
   debug_utils | >>> Memory READ at 0xa012b8dc, data size = 4, pc: a012b8a4, data value = 0x56870800
      __main__ | # Tracing PC=0xa012b8a6, instruction size=2: 78 44 	 add r0, pc
      __main__ | # Tracing PC=0xa012b8a8, instruction size=2: 24 30 	 adds r0, #0x24
      __main__ | # Tracing PC=0xa012b8aa, instruction size=4: d0 e8 af 0f 	 lda r0, [r0]
      __main__ | ====== Registers Dump ======
      __main__ | X00: 0x00000000a01b4024
      __main__ | X01: 0x00000000a0155f25
      __main__ | X02: 0x00000000a0155f25
      __main__ | X03: 0x0000000000000000
      __main__ | X04: 0x000000000000000a
      __main__ | X05: 0x00000000a0155f25
      __main__ | X06: 0x00000000101fedb0
      __main__ | X07: 0x00000000101fefe8
      __main__ | X08: 0x000000000000001a
      __main__ | X09: 0x0000000000000000
      __main__ | X10: 0x0000000080808081
      __main__ | X11: 0x0000000010eac63e
      __main__ | X12: 0x00000000a0631af4
      __main__ | X13: 0x00000000101fed78
      __main__ | X14: 0x00000000a0606d2f
      __main__ | X15: 0x00000000a012b8aa
      __main__ | 

      __main__ | SP:  0x00000000101fed78
      __main__ | PC:  0x00000000a012b8aa
      __main__ | ============================

          root | Emulation error: Invalid instruction (UC_ERR_INSN_INVALID)

examples git:(master) ✗ r2 example_binaries/arm64/lib/libc.so
ERROR: Cannot determine entrypoint, using 0x0002ac00
WARN: Relocs has not been applied. Please use `-e bin.relocs.apply=true` or `-e bin.cache=true` next time
 -- radare2 contributes to the One Byte Per Child foundation.
[0x0002ac00]> aaa
INFO: Analyze all flags starting with sym. and entry0 (aa)
INFO: Analyze imports (af@@@i)
INFO: Analyze entrypoint (af@ entry0)
INFO: Analyze symbols (af@@@s)
WARN: Basic block at 0x0009cb6c is too large
INFO: Analyze all functions arguments/locals (afva@@@F)
INFO: Analyze function calls (aac)
INFO: Analyze len bytes of instructions for references (aar)
INFO: Finding and parsing C++ vtables (avrr)
INFO: Analyzing methods (af @@ method.*)
INFO: Emulate functions to find computed references (aaef)
INFO: Recovering local variables (afva@@@F)
INFO: Type matching analysis for all functions (aaft)
INFO: Propagate noreturn information (aanr)
INFO: Use -AA or aaaa to perform additional experimental analysis
INFO: Finding xrefs in noncode sections (e anal.in=io.maps.x; aav)
[0x0002ac00]> afl | grep 2b8a0
0x0002b8a0    4     36 sym.malloc
[0x0002ac00]> s sym.malloc
[0x0002b8a0]> pdf
┌ 36:  void *sym.malloc (size_t size);
│ `- args(r0)
│           0x0002b8a0      b0b5           push {r4, r5, r7, lr}
│           0x0002b8a2      0446           mov r4, r0                  ; size
│           0x0002b8a4      0d48           ldr r0, [0x0002b8dc]        ; [0x2b8dc:4]=0x88756
│           0x0002b8a6      7844           add r0, pc                  ; 0xb4000
│                                                                      ; obj.__libc_globals
│           0x0002b8a8      2430           adds r0, 0x24
│           0x0002b8aa      d0e8af0f       lda r0, [r0]
│       ┌─< 0x0002b8ae      80b9           cbnz r0, 0x2b8d2
│       │   0x0002b8b0      2046           mov r0, r4                  ; int16_t arg1
│       │   0x0002b8b2      05f017f8       bl sym.scudo_malloc
│       │   ; CODE XREF from sym.malloc @ 0x2b8d8(x)
│      ┌──> 0x0002b8b6      0028           cmp r0, 0
│      ╎│   0x0002b8b8      18bf           it ne
│      ╎│   0x0002b8ba      b0bd           pop {r4, r5, r7, pc}
..
│      ╎│   ; CODE XREF from sym.malloc @ 0x2b8ae(x)
│      ╎└─> 0x0002b8d2      c168           ldr r1, [r0, 0xc]
│      ╎    0x0002b8d4      2046           mov r0, r4
│      ╎    0x0002b8d6      8847           blx r1
└      └──< 0x0002b8d8      ede7           b 0x2b8b6
[0x0002b8a0]>

This error occurs in the libc.so library of an Android application when executing the malloc function. The program is a 32-bit application running on an ARM64 chip in ​Thumb mode​ (UC_MODE_THUMB). Could this be caused by a specific instruction?

**Comment by wtdcode** [comment]
https://github.com/unicorn-engine/unicorn/wiki/FAQ#emulating-some-instructions-gives-an-error-like-invalid-instruction-what-should-i-do
