### ISSUE TITLE
Pointers to sections that I get through uc_mem_map

### ISSUE THREAD

**Issue by OSPFvX** [unicorn-engine/unicorn#1755]
Hello everyone! 

uc_mem_map allocates a VA section into which Unicorn patches as the code passes, now I need to get pointers to these sections in order to write them to my .exe. Through uc_mem_regions(); I get the same VA each time and the number of blocks that does not match the allocated uc_mem_map, as well as the size that also does not match the allocated size.. well, I can't write down the data that UNICORN patched, respectively, since I can't get pointers to this whole thing

I get this from uc_mem_regions() https://ibb.co/tLY8zVh
Instead of the necessary pointers

How can I get a pointer to the memory that uc_mem_map allocated?

SIZE\ADDRESSES 
```
#define ASectionSdataDenuvo 0x140001000
#define ASectionArchDenuvo 0x141C97000
#define ASectionBssDenuvo 0x142AC5000
#define ASectionPdataDenuvo 0x142D56000
#define ASectionTraceDenuvo 0x142E78000
#define ASectionTlsDenuvo 0x142E7A000
#define ASectionSrdataDenuvo 0x15B220000
#define ASectionEdataDenuvo 0x15B276000
#define ASectionIdataDenuvo 0x15B282000
#define ASectionXtextDenuvo 0x15B283000
#define ASectionXtlsDenuvo 0x15B284000
#define ASectionTextDenuvo 0x15B285000
#define ASectionCodeDenuvo 0x15B28D000

int64_t ADDRESS_TEXT_SECTION_NTDLL, ADDRESS_TEXT_SECTION_MSVCRT;

uint64_t SIZE_Section_Sdata_Denuvo = 0x1C96000;
uint64_t SIZE_Section_Arch_Denuvo = 0xE2E000;
uint64_t SIZE_Section_Bss_Denuvo = 0x291000;
uint64_t SIZE_Section_Pdata_Denuvo = 0x122000;
uint64_t SIZE_Section_Trace_Denuvo = 0x2000;
uint64_t SIZE_Section_Tls_Denuvo = 0x183A6000;
uint64_t SIZE_Section_Srdata_Denuvo = 0x56000;
uint64_t SIZE_Section_Edata_Denuvo = 0xC000;
uint64_t SIZE_Section_Idata_Denuvo = 0x1000;
uint64_t SIZE_Section_Xtext_Denuvo = 0x1000;
uint64_t SIZE_Section_Xtls_Denuvo = 0x1000;
uint64_t SIZE_Section_Text_Denuvo = 0x8000;
uint64_t SIZE_Section_Code_Denuvo = 0x1B000;

uint64_t SIZE_Section_Text_Ntdll = 0x119000;
uint64_t SIZE_Section_Text_Msvcrt = 0x75000;
```
uc_mem_map I have such a quantity and it does not correspond to 11 blocks in any way
```
0) uc_mem_map(uc, STACK_ADDRESS, SIZE_OF_STACK, UC_PROT_ALL);

1) uc_mem_map(uc, ASectionSdataDenuvo, SIZE_Section_Sdata_Denuvo, UC_PROT_ALL);
2) uc_mem_map(uc, ASectionArchDenuvo, SIZE_Section_Arch_Denuvo, UC_PROT_ALL);
3) uc_mem_map(uc, ASectionBssDenuvo, SIZE_Section_Bss_Denuvo, UC_PROT_ALL);
4) uc_mem_map(uc, ASectionPdataDenuvo, SIZE_Section_Pdata_Denuvo, UC_PROT_ALL);
5) uc_mem_map(uc, ASectionTraceDenuvo, SIZE_Section_Trace_Denuvo, UC_PROT_ALL);
6) uc_mem_map(uc, ASectionTlsDenuvo, SIZE_Section_Tls_Denuvo, UC_PROT_ALL);
7) uc_mem_map(uc, ASectionSrdataDenuvo, SIZE_Section_Srdata_Denuvo, UC_PROT_ALL);
8) uc_mem_map(uc, ASectionEdataDenuvo, SIZE_Section_Edata_Denuvo, UC_PROT_ALL);
9) uc_mem_map(uc, ASectionIdataDenuvo, SIZE_Section_Idata_Denuvo, UC_PROT_ALL);
10) uc_mem_map(uc, ASectionXtextDenuvo, SIZE_Section_Xtext_Denuvo, UC_PROT_ALL);
11) uc_mem_map(uc, ASectionXtlsDenuvo, SIZE_Section_Xtls_Denuvo, UC_PROT_ALL);
12) uc_mem_map(uc, ASectionTextDenuvo, SIZE_Section_Text_Denuvo, UC_PROT_ALL);
13) uc_mem_map(uc, ASectionCodeDenuvo, SIZE_Section_Code_Denuvo, UC_PROT_ALL);

14) uc_mem_map(uc, ADDRESS_TEXT_SECTION_NTDLL, SIZE_Section_Text_Ntdll, UC_PROT_ALL);
15) uc_mem_map(uc, ADDRESS_TEXT_SECTION_MSVCRT, SIZE_Section_Text_Msvcrt, UC_PROT_ALL);

16) uc_mem_map(uc, GS_BASE_ADDRESS, SIZE_OF_GDT_BASE, UC_PROT_ALL);
```
implementation of uc_mem_regions();

```
if (address == 0x156265A75)
    {
        uc_err err;
        uc_mem_region* region;
        uint32_t count;

        if ((err = uc_mem_regions(uc, &region, &count))) {
            std::cout << "Failed on uc_mem_regions() with error returned %u: %s" << err << uc_strerror(err) << endl;
        }

        cout << "Starting address: 0x" << hex << region->begin << " End address: 0x" << hex << region->end << " Memory permissions: " << region->perms << " Number of memory blocks requested: " << count << endl << endl << endl << endl;
    }
```

**Comment by wtdcode** [comment]
Did you check uc_mem_map_ptr?
________________________________
From: OSPFvX ***@***.***>
Sent: Wednesday, January 4, 2023 1:07:08 AM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] Pointers to sections that I get through uc_mem_map (Issue #1755)


Hello everyone!

uc_mem_map allocates a VA section into which Unicorn patches as the code passes, now I need to get pointers to these sections in order to write them to my .exe. Through uc_mem_regions(); I get the same VA each time and the number of blocks that does not match the allocated uc_mem_map, as well as the size that also does not match the allocated size.. well, I can't write down the data that UNICORN patched, respectively, since I can't get pointers to this whole thing

How can I get a pointer to the memory that uc_mem_map allocated?

SIZE\ADDRESSES

#define ASectionSdataDenuvo 0x140001000
#define ASectionArchDenuvo 0x141C97000
#define ASectionBssDenuvo 0x142AC5000
#define ASectionPdataDenuvo 0x142D56000
#define ASectionTraceDenuvo 0x142E78000
#define ASectionTlsDenuvo 0x142E7A000
#define ASectionSrdataDenuvo 0x15B220000
#define ASectionEdataDenuvo 0x15B276000
#define ASectionIdataDenuvo 0x15B282000
#define ASectionXtextDenuvo 0x15B283000
#define ASectionXtlsDenuvo 0x15B284000
#define ASectionTextDenuvo 0x15B285000
#define ASectionCodeDenuvo 0x15B28D000

int64_t ADDRESS_TEXT_SECTION_NTDLL, ADDRESS_TEXT_SECTION_MSVCRT;

uint64_t SIZE_Section_Sdata_Denuvo = 0x1C96000;
uint64_t SIZE_Section_Arch_Denuvo = 0xE2E000;
uint64_t SIZE_Section_Bss_Denuvo = 0x291000;
uint64_t SIZE_Section_Pdata_Denuvo = 0x122000;
uint64_t SIZE_Section_Trace_Denuvo = 0x2000;
uint64_t SIZE_Section_Tls_Denuvo = 0x183A6000;
uint64_t SIZE_Section_Srdata_Denuvo = 0x56000;
uint64_t SIZE_Section_Edata_Denuvo = 0xC000;
uint64_t SIZE_Section_Idata_Denuvo = 0x1000;
uint64_t SIZE_Section_Xtext_Denuvo = 0x1000;
uint64_t SIZE_Section_Xtls_Denuvo = 0x1000;
uint64_t SIZE_Section_Text_Denuvo = 0x8000;
uint64_t SIZE_Section_Code_Denuvo = 0x1B000;

uint64_t SIZE_Section_Text_Ntdll = 0x119000;
uint64_t SIZE_Section_Text_Msvcrt = 0x75000;


uc_mem_map I have such a quantity and it does not correspond to 11 blocks in any way

0) uc_mem_map(uc, STACK_ADDRESS, SIZE_OF_STACK, UC_PROT_ALL);

1) uc_mem_map(uc, ASectionSdataDenuvo, SIZE_Section_Sdata_Denuvo, UC_PROT_ALL);
2) uc_mem_map(uc, ASectionArchDenuvo, SIZE_Section_Arch_Denuvo, UC_PROT_ALL);
3) uc_mem_map(uc, ASectionBssDenuvo, SIZE_Section_Bss_Denuvo, UC_PROT_ALL);
4) uc_mem_map(uc, ASectionPdataDenuvo, SIZE_Section_Pdata_Denuvo, UC_PROT_ALL);
5) uc_mem_map(uc, ASectionTraceDenuvo, SIZE_Section_Trace_Denuvo, UC_PROT_ALL);
6) uc_mem_map(uc, ASectionTlsDenuvo, SIZE_Section_Tls_Denuvo, UC_PROT_ALL);
7) uc_mem_map(uc, ASectionSrdataDenuvo, SIZE_Section_Srdata_Denuvo, UC_PROT_ALL);
8) uc_mem_map(uc, ASectionEdataDenuvo, SIZE_Section_Edata_Denuvo, UC_PROT_ALL);
9) uc_mem_map(uc, ASectionIdataDenuvo, SIZE_Section_Idata_Denuvo, UC_PROT_ALL);
10) uc_mem_map(uc, ASectionXtextDenuvo, SIZE_Section_Xtext_Denuvo, UC_PROT_ALL);
11) uc_mem_map(uc, ASectionXtlsDenuvo, SIZE_Section_Xtls_Denuvo, UC_PROT_ALL);
12) uc_mem_map(uc, ASectionTextDenuvo, SIZE_Section_Text_Denuvo, UC_PROT_ALL);
13) uc_mem_map(uc, ASectionCodeDenuvo, SIZE_Section_Code_Denuvo, UC_PROT_ALL);

14) uc_mem_map(uc, ADDRESS_TEXT_SECTION_NTDLL, SIZE_Section_Text_Ntdll, UC_PROT_ALL);
15) uc_mem_map(uc, ADDRESS_TEXT_SECTION_MSVCRT, SIZE_Section_Text_Msvcrt, UC_PROT_ALL);

16) uc_mem_map(uc, GS_BASE_ADDRESS, SIZE_OF_GDT_BASE, UC_PROT_ALL);


implementation of uc_mem_regions();

if (address == 0x156265A75)
    {
        uc_err err;
        uc_mem_region* region;
        uint32_t count;

        if ((err = uc_mem_regions(uc, &region, &count))) {
            std::cout << "Failed on uc_mem_regions() with error returned %u: %s" << err << uc_strerror(err) << endl;
        }

        cout << "Starting address: 0x" << hex << region->begin << " End address: 0x" << hex << region->end << " Memory permissions: " << region->perms << " Number of memory blocks requested: " << count << endl << endl << endl << endl;
    }


―

**Comment by OSPFvX** [comment]
> Did you check uc_mem_map_ptr?

Hmm, no, I didn't check it.
But it seems like I solved the problem in another way, what uc_mem_map does is allocate memory at the address I set, I just started putting a pointer in the WriteFile to the memory I set in uc_mem_map, i.e. I don't even use uc_mem_regions() and everything seems to work.

I also dug into the giblets of UNICORN and the qemu_alloc_memory function still returns a pointer to qemu_memory_map_x86-x64, but then it is saved to some UNIOCRN structure, through the x64 dbg debugger I can't see the name of the structure, but it is clearly saved somewhere.

Also uc_mem_region returns the address of only the very first block that I allocated via uc_mem_map, the others are not returned via uc_mem_regions()

I will now add 1000 lines and post an example of how I implemented it, I will ask you not to close the issue, I will close it myself.

**Comment by OSPFvX** [comment]
> Did you check uc_mem_map_ptr?
I fucked up, it doesn't fucking work either. How can uc_mem_map_ptr help me?

**Comment by OSPFvX** [comment]
I came up with a crutch!

   ```
VirtualAddresForWrite = VirtualAlloc(NULL, SIZE_Section_Tls_Denuvo, MEM_COMMIT, PAGE_EXECUTE_READWRITE);

    uc_mem_read(uc, 0x142E7A000, VirtualAddresForWrite, SIZE_Section_Tls_Denuvo);

    mbstowcs(text, PathToFile, strlen(PathToFile) + 1);

    hFile = CreateFileW((LPCWSTR)text, GENERIC_WRITE, 0, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
    if (hFile == INVALID_HANDLE_VALUE)
    {
        MessageBox(NULL, (LPCSTR)"Couldn't open the input file!", (LPCSTR)"Error", MB_ICONERROR);
    }
   
    size_t dwFileSize = GetFileSize(hFile, NULL);
    if (dwFileSize == 0)
    {
        CloseHandle(hFile);

        MessageBox(NULL, (LPCSTR)"Input file is empty (0 bytes)!", (LPCSTR)"Error", MB_ICONERROR);
    }

    SetFilePointer((HANDLE)hFile, ARawSectionTlsDenuvo, 0, FILE_BEGIN);
    BOOL bReadFileResult = WriteFile(hFile, (LPVOID)VirtualAddresForWrite, SIZE_Section_Tls_Denuvo, NULL, NULL);
    if (bReadFileResult == FALSE)
    {
        CloseHandle(hFile);

        MessageBox(NULL, (LPCSTR)"An error occured while reading bytes from file!", (LPCSTR)"Error", MB_ICONERROR);
    }
```
