### ISSUE TITLE
.NET Binding - Structured Exception Handling

### ISSUE THREAD

**Issue by 9ee1** [unicorn-engine/unicorn#179]
Hello:

The expected and standard practice for dealing with errors in .NET is to properly have the API throw exceptions when an operation fails. It allows structured handling or propagation of the exception by application code.

Application code should not be expected to call `Utils.CheckError` to determine if an error code exists and then have that utility throw an exception. Instead, when I invoke a method like `Unicorn. RegWrite`, that method itself should throw an exception if there is a problem.

Consider creating a base exception, something like `UnicornException` to denote what type of exception the API can throw.

In addition, your current implementation is not thread safe.

**Comment by enkomio** [comment]
Hi,
I have decided to not use the exception mechanism, at least for now, in order to have a strong adherence with the native public API.

However, I'll evaluate the use of exceptions in a future release.

**Comment by lunixbochs** [comment]
The native API doesn't use exceptions because C doesn't have them.

The first-party Python API does use exceptions. My stance is you should use them for the bindings if your language has them.

**Comment by 9ee1** [comment]
I agree with @lunixbochs on this. The native API does not use exceptions because C doesn't have them. An API should take advantage of the features the programming language it is written in.

Besides, most .NET developers will expect some form of structured exception handling.

**Comment by JonathonReinhart** [comment]
I haven't looked at the Java or Go bindings, but this is a general deficiency of the Python bindings as well.   They are very idiomatic of C, and aren't particularly "Pythonic". I had intended on adding wrappers to correct this, but was waiting to see what came out of #6, which proposed using CFFI to implement the bindings.

**Comment by enkomio** [comment]
Guys, thanks for the clarification, but I am aware that C doesn't have exception :)

When I have done the binding I had to decide if strictly follow the native API or not. In some case I have used the .NET standard (see for example the methods name convention) and in other case I have followed an adherence with the native API (like the error management and the usage of not CLS compliant data type, see #182 ).

In my opinion all the binding should follow a common design choice, if you see the java binding it use the exception but not a "standard" java naming convention for the methods name (the opposite thing done by me :P).

However, I think that it is important to provide an API that is clean and intuitive, I see in your comments a strong preference for using exception and not errors code, so I will change the code in order to use exception.

**Comment by aquynh** [comment]
yes, it is a good idea to closely follow the core API, so it is easier for people to switch from one binding to another without having to learn much new things. meanwhile, it is better have some adjustments to make the binding more natural to its language. so the point is how to balance these things.

**Comment by JonathonReinhart** [comment]
I disagree. I think the bindings should *fully* leverage the capabilities of the language, and fully conform to their naming conventions and common idioms. The whole point of having multiple language bindings is to make a library more comfortable to use for users of a particular language.  The people picking up Unicorn and coding against it in their preferred language will **vastly** outnumber the people who want to switch between languages when using Unicorn. If the library is comfortable to use in a given language, it will be easy to pick up, even if it varies slightly between languages. Native API be damned :smile: 

We should *absolutely* be throwing exceptions in all languages that support them, because it eliminates the need for tiresome error-checking, which many people are willing to neglect. Just look at [`samples/sample_x86.c`](https://github.com/unicorn-engine/unicorn/blob/master/samples/sample_x86.c)!  Even our own sample code is a poor example of how to use the library.

**Comment by aquynh** [comment]
agreed on using exceptions if the language allows that.

on to follow the API, i mean that if the core API is cs_open(), it is better to have binding API as CsOpen, but not good to rename that to CsIntialize(), for example.

**Comment by JonathonReinhart** [comment]
Yes, although it'd be okay if the native call were hidden in the constructor; that would be even better.

**Comment by aquynh** [comment]
yes, that is how Python binding works.

**Comment by enkomio** [comment]
commit d92bee414dbcc71fca476ba6cb0ec946edd3d19d should have resolved this issue.

**Comment by 9ee1** [comment]
I confirm. Thanks!
