### ISSUE TITLE
.NET Binding - CLS Compliant Data Types

### ISSUE THREAD

**Issue by 9ee1** [unicorn-engine/unicorn#182]
Hello:

This is more of a question and not an issue, but why aren't you using CLS Compliant Data Types? Is it a restriction of the Unicorn native API? A CLS Compliant API will guarantee of interoperability with a wide range of programming languages in case not all your users can/interested in consuming your API in F#.

**Comment by enkomio** [comment]
Hi,

I have used not CLS compliant type in order to have a strong adherence with the native public API. Even if not CLS compliant, the library can be used with both F# and C# (and I suppose even VB.NET). The problem will arise in case of usage of languages that don't support unsigned type.

I don't known how much this can be a real issue. However I'll verify if the changes to a CLS compliant data type will works as expected.

**Comment by enkomio** [comment]
Hi,

the Unicorn class now exposes methods with only CLS compliant parameter types.
