### ISSUE TITLE
Visual Studio support?

### ISSUE THREAD

**Issue by Normmatt** [unicorn-engine/unicorn#185]
Any plans to support Visual Studio?

**Comment by aquynh** [comment]
no so far. hopefully community will step up for this job :-)

**Comment by farmdve** [comment]
QEMU uses some gcc extensions so refactoring of the code will be needed, unless VC supports them. E.g the ellipsis for switch statements and attributes.

**Comment by aquynh** [comment]
This will be a hard work for sure. But supporting MSVC for Unicorn is much easier than Qemu because the code size is order of magnitude  smaller. Still hope someone will step up for this job.

**Comment by xorstream** [comment]
I did some code to load the precompiled dlls in MSVC thereby allowing you to develop apps in MSVC that use the unicorn engine. If this is what you are after I'll see if I can work out how to provide access to these files via a git :)

**Comment by aquynh** [comment]
this sounds useful. if you dont mind including this into Unicorn code so others can benefit from your work, please send a pull request. thanks.

**Comment by xorstream** [comment]
Code submitted in the same fork as the MIPS delay slot test pull request.
It lets you statically and dynamically link in the prebuilt 32bit and 64bit dlls.

**Comment by robhshu** [comment]
The MSVC samples were merged in #297.

This issue should be closed.

**Comment by farmdve** [comment]
I tried to build the tests from latest master, they fail. The error seems to indicate it can't find unicorn.lib, but I use mingw.

**Comment by xorstream** [comment]
When you build unicorn do you get a unicorn.lib file or a libunicorn.a file?

I added a check into the tests/regress/Makefile to look for unicorn.lib if you are using ming, and libunicorn.a otherwise. So maybe your unicorn build didnt complete or it is looking for libunicorn.a

**Comment by farmdve** [comment]
I build with this UNICORN_ARCHS="x86" ./make.sh. Nothing else. It generates an archive.

**Comment by xorstream** [comment]
So you end up with a libunicorn.a file?
I guess the following lines will need altering:

ifeq (MING,$(findstring MING,$(shell uname -s)))
LDFLAGS += ../../unicorn.lib $(shell pkg-config --libs glib-2.0) -lpthread -lm
else
LDFLAGS += ../../libunicorn.a $(shell pkg-config --libs glib-2.0) -lpthread -lm
endif


What does uname return on your system?
For me with mingw-w64 and msys2 it returns:
MINGW32_NT-10.0 WinHate 2.3.0(0.291/5/3) 2015-11-06 08:17 x86_64 Msys

**Comment by farmdve** [comment]
Similar output to yours, but your lines are reversed. .a for MinGW and .lib for MSVC.

**Comment by xorstream** [comment]
I am using mingw-w64 to build unicorn with: ./make.sh cross-win32.
Then I built the tests with: make CC=i686-w64-mingw32-gcc
I end up with a unicorn.lib file.

The check was supposed to differentiate between building like this and building on a more normal linux system. It is not related to MSVC at all. So the check needs to be changed to differentiate between your mingw style of building and mine. That is why I ask what uname returns for you so that the check can be altered.

**Comment by farmdve** [comment]
MINGW32_NT-6.1 WINDOWS7 2.3.0(0.290/5/3) 2015-10-20 10:04 x86_64 Msys

**Comment by xorstream** [comment]
Looking in the Makefile for unicorn itself (not the tests) I see at line 111:

# mingw?
IS_MINGW := $(shell $(CC) --version | grep -i mingw | wc -l)
ifeq ($(IS_MINGW),1)
EXT = dll
AR_EXT = lib
BIN_EXT = .exe
else

Which would make me think that mingw builds should produce a .lib file.
Perhaps you can make some changes to the tests Makefile using these checks since these same checks are what determines the name of the generated library file.

**Comment by aquynh** [comment]
this is already done in the "msvc" branch. will merge that into "master" soon.
