### ISSUE TITLE
Move build system to SCons?

### ISSUE THREAD

**Issue by JonathonReinhart** [unicorn-engine/unicorn#200]
[SCons](http://scons.org/) is a very nice build system, and it [handles shared object versioning natively](http://stackoverflow.com/a/20840744/119527). The other huge advantage of SCons is that it automatically handles lots of the autoconf-like platform-specific stuff without having to do a bunch of `if`s all over your `Makefile`.

I think it would be straightforward to move Unicorn to SCons.  And even though QEMU is embedded, I have written code in the past that handles building an autoconf and `Makefile`-based project from SCons, which I would be willing to share. It might not be necessary.

Is this something you would consider?

**Comment by aquynh** [comment]
i dont think it is worth changing for following reasons:

- Makefile setup is clean, well understood (by me and many others), easy to maintain, and universal supported everywhere. it is much easier for everybody to compile & install Unicorn this way.

- the current issue with unit test can be fixed with very little modification, without having to switch everything to SCons just for this.

**Comment by JonathonReinhart** [comment]
I didn't really think it would be worth the effort, but wanted to throw it out there to see what people thought.

**Comment by radare** [comment]
Nope
