### ISSUE TITLE
new API uc_mem_map_ptr()

### ISSUE THREAD

**Issue by aquynh** [unicorn-engine/unicorn#279]
thanks to @lunixbochs, we have a new API uc_mem_map_ptr() now living in the "map-ptr" branch.

    uc_err uc_mem_map_ptr(uc_engine *uc, uint64_t address, size_t size, uint32_t perms, void *ptr);

see its docs at 
https://github.com/unicorn-engine/unicorn/blob/map-ptr/include/unicorn/unicorn.h#L469

as pointed out by Ryan: "this API allows you to map guest memory regions backed by a host-controlled pointer. This allows the user to fully control the backing memory, including any platform-specific functions like memory mapping files."

this is a nice API to have, but there are still few major concerns:

- the permission of memory given to `uc_mem_map_ptr()` is not controlled by Unicorn, and there is no portable way to retrieve it. what if this memory is allocated with wrong permission, or what if the permission is changed externally at run-time (such as by using mprotect())? how should we handle errors when that happens?

- the memory is allocated outside of Unicorn, thus can be manipulated without its awareness. example: if we change the code inside the memory, we need to tell Unicorn about that. this is not considered at the moment.

please comment on this API.

**Comment by lunixbochs** [comment]
For permissions, I think we can't do much except declare memory that's not read+write on the host as "undefined behavior".

For memory outside Unicorn, I think that only matters if you map in code then change it later. Unless I'm mistaken, all QEMU can do here is provide a "flush this page" API, or mark the TB as volatile and check a hash or something before entry.

**Comment by aquynh** [comment]
can you find out (by writing some sample code) what happens if wrong permission is given to this API? and in such a case, to which extent we can handle the errors?

**Comment by lunixbochs** [comment]
It will segfault. You can handle it by catching segfault. I don't think Unicorn can deal with this portably.

**Comment by aquynh** [comment]
to be sure, should we call `mprotect()` to set permission for the memory passed in according to the *perms* argument?

**Comment by lunixbochs** [comment]
No. I really don't think so. This is an advanced API, and I don't think it's good to mess with whatever low-level stuff the user is trying to do. mprotect won't fix all cases anyway.

Some examples:

1. You map in some RX host memory, but you tell Unicorn to map it read-only. You try to jump to the memory from the host. mprotect would break this.

2. You mmap a read-only or write-only file. mprotect doesn't help here.

3. You map the same memory segment into multiple Unicorn instances with different permissions (read-only in one, read-write in the next, read-write-execute in the third). mprotect could break this if it happened in the wrong order.

I really think it's the user's job to make sure the memory is in the right state here.

**Comment by bunnei** [comment]
I'm interested in experimenting with Unicorn in my emulation projects, and for most of my applications the ability to manage my own backing memory is pretty critical. Are there plans to mainline this feature?

**Comment by aquynh** [comment]
@bunnei: can you tell more on how you are using this API?

still having some concerns about the problems i post above. therefore, i am trying to understand how people will use this, but the intention is to merge it into "master" branch eventually.

**Comment by lunixbochs** [comment]
FWIW, my primary use for this right now is something like:

    void *mmap_file(guest_addr, size, prot, fd) {
        void *host_addr = mmap(0, size, prot, fd);
        uc_mem_map_ptr(handle, guest_addr, size, prot, host_addr);
        return guest_addr;
    }

**Comment by bunnei** [comment]
@aquynh, I run [Citra](https://github.com/citra-emu/citra), a Nintendo 3DS emulator. We do not currently use Unicorn for our CPU emulation, but I'm interested in using it for a few reasons:
* To compare accuracy with our current CPU core (interpreter)
* As an alternative to writing a JIT (for speed), so long as Unicorn provides the flexibility, accuracy, & performance that we need
* To simplify our code base (so that we could focus on 3DS-specific features, rather than fast/accurate ARM emulation)

Regarding the aforementioned feature, there are several reasons that I would like this, among them: 
* We already manage the 3DS memory layout in a way that is agnostic to our CPU core, and we would like to just reuse this with Unicorn rather than having a separate code path that maps the memory via Unicorn
* Furthermore, we will probably always want to have the ability to have multiple CPU emulation backends, such as to debug/compare and also to target different host architectures (e.g. an ARM-based JIT for Android or something), and therefore we want a unified memory management system
* To have more control over the memory layout, e.g. for debugging, MMIO, mirroring, paging, etc. (perhaps some of this is already supported in a nice way by Unicorn; but without more experience/knowledge of your software I don't really have the means to suggest improvements/features that would help us at this time)

If you're interested, [here](https://github.com/citra-emu/citra/blob/master/src/core/hle/kernel/vm_manager.cpp) is where we currently manage our virtual memory. I envisioned that we would use this system still when using Unicorn, but simply call `uc_mem_map_ptr` (or some similiar API function) to map all of the regions that we allocated/loaded our code into.

**Comment by aquynh** [comment]
if i understand correctly, you just map some memory areas in with `uc_mem_map_ptr()`, but will not access them from outside of the emulator while emulation happens?

**Comment by bunnei** [comment]
@aquynh basically; we still will need to access these memory regions outside of CPU emulation when emulating other subsystems (e.g. shared memory between the emulated application and the OS high-level emulation, GPU memory accessed by our video core, etc.), but it should never be concurrent to CPU access.

**Comment by radare** [comment]
Do you think it will be possible to have pull mode memory access by providing mem-read and mem-write callbacks instead of fully mapping the file or allocating the memory?

**Comment by lunixbochs** [comment]
callbacks have a ton of overhead as they're per instruction and add a stack frame. it's like doing a syscall to read four bytes.

**Comment by aquynh** [comment]
i dont see how to use this API with Python binding. should we remove it in Python binding?

**Comment by lunixbochs** [comment]
No, we should leave it. It's possible to use this API with Python using ffi. You can ctypes.LoadLibrary(libc) and call mmap/munmap to create appropriate memory regions.

**Comment by aquynh** [comment]
i merged "map-ptr" branch into "master" branch, thanks!
