### ISSUE TITLE
[mips] delay slot handling while stepping

### ISSUE THREAD

**Issue by ZakDanger** [unicorn-engine/unicorn#332]
This ties in with the other delay slot issues such as issue #330 for mips and so should be considered when implementing their fix.

I have come across another related issue to the mips branch delay problems. It may be considered that this is just how unicorn works with regards to delay slots. But in doing so it puts a lot of work in the hands of the unicorn user that is really best handled by the emulator at the heart of unicorn. See the "Possible way to have this #3" below for more info.

:: Problem

If you step through code by doing uc_emu_start() and specifying to execute 1 instruction each time then there are issues handling whether you are in a branch delay slot or not. Consider the following.

1) You get to an instruction that has a delay slot, such as branch or jump, it will call the code hook but it won't do the branch or jump yet because it has to first handle the delay slot.
2) Next you get to the delay slot instruction which will call the code hook for it.
3) Next it incorrectly calls the instruction immediately after the delay slot instruction because it has forgotten that the initial instruction that had the delay slot was called and thinks that it just started executing code at the delay slot instruction.

Here is an example showing mips instructions:
0000: nop
0004: jal  some_func
0008: li  a0, 1
000C: li  v0, 2

So if stepping through executing one instruction at a time in this case, it effetively execute all instructions linearly except for the "jal some_func" which will not end up getting executed at all.

:: Possible ways to handle this?

1) Unicorn remembers register values across multiple calls to uc_emu_start(). It does not clear them to zero each time, which is handy when using unicorn to step through code. So perhaps it could also remember if it is in a branch delay slot too? Maybe the flag for whether it is in a branch delay slot or not would only be used if starting again from the same PC address. So the branch delay flag would be tied in with the PC address.

2) Perhaps there could be a way to manually set a flag indicating to start executing code as if it was in a branch delay slot.

3) Leave it up to the unicorn user to watch out for such occurrences and manually adjust the PC themselves. At first glance this may seem the easy way out. However it means that every user would have to handle every instruction with a delay slot. This includes:
- detecting which instructions have a delay slot
- extracting the target address of the branch or jump
- determining whether a branch or jump is taken (for conditional branches/jumps)
  Having to handle all 3 of these for every instruction with a delay slot doesn't seem to me something that the user should have to take care of. It is something that the emulator should take care of since that is exactly what it is there for! :)

4) Some other idea??

**Comment by xorstream** [comment]
To add some more info to the discussion:

http://www.cs.cmu.edu/afs/cs/academic/class/15740-f97/public/doc/mips-isa.pdf
On "PDF page 20" (labelled as A-8)
It mentions that:
"By convention, if an exception or interrupt prevents the completion of an
instruction occupying a branch delay slot, the instruction stream is continued by
re-executing the branch instruction. To permit this, branches must be restartable;
procedure calls may not use the register in which the return link is stored (usually
register 31) to determine the branch target address."

This suggests to me that after executing a delay slot instruction that causes an exception, as it would if stepping over it, then it would then process the branch instruction to do the actual branching after the delay slot exception is handled.


Also I tried debugging with gdb and i found that it would not "step" onto any delay slot instruction. It acted as if they did not exist as far as the stepping flow went.


I am looking at this from the point of a debugger stepping through code. But when it comes down to it a unicorn user should be able to get a code hook on any instruction executed including delay slot instructions, since there will undoubtably be many cases where it is useful to do so. Also there will be cases where users will want to stop and process such things and then continue the code executing again.

Perhaps other ideas for handling this then are:

4) Have a way to "pause"/"unpause" execution of the emulator. This would be much like uc_emu_start()/uc_emu_stop() work now, however it would retain other state info such as whether the CPU is currently executing a delay slot instruction.

5) Make uc_emu_start()/uc_emu_stop() work like the pause/unpause suggestions above, and so retaining the "is in delay slot" state. But then add another function like uc_emu_clear() or uc_emu_reset() that would reset all states and clear all registers to zero. I can actually see such a function being quite useful if you are reusing an emu implementation over and over and want to ensure you start fresh each time without also having to do an uc_open()/uc_close() each time.

** So far I think #5 is the best idea for handling this.

**Comment by xorstream** [comment]
I had another related thought to this issue today. It has to do with the difference between instruction fetches and instruction execution.

For delay slots the instruction fetches are "in order" but instruction execution is "out of order".
Using the following MIPS example code:
0000: nop
0004: jal some_func
0008: li a0, 1
000C: li v0, 2

Instruction fetches would occur at addresses: 0, 4, 8, then C.
Instruction execution would occur at addresses: 0, 8, 4, then C.
This is because the CPU executes the instruction at address 8 while the 'jal' at address 4 is still in the pipeline being processed.

So from a purely CPU point of view:
a UC_HOOK_CODE_FETCH would be called back in the order: 0, 4, 8, C.
a UC_HOOK_CODE_EXEC would be called back in the order: 0, 8, 4, C.

Do you see where I am going with this?
So currently we have UC_HOOK_CODE (and also UC_MEM_FETCH but is that called for instruction fetches?) So if we split UC_HOOK_CODE into UC_HOOK_CODE_FETCH and UC_HOOK_CODE_EXEC then we could get callbacks occurring in either order. For CPUs with no delay slot then the two would be equivalent. And for backwards compatibility we could have UC_HOOK_CODE be the same as UC_HOOK_CODE_FETCH.

"That's crazy talk. No one's ever done that before! Why would we bother?"
Dealing with delay slots sucks. You know it, I know it, unicorn users know it.
Imagine a world where you didn't have deal with asm where the instructions are not executed in the order they are written... (But still retain the freedom to do so if required via the FETCH callback).
So a unicorn user can hook the code execution, and they don't have to specially handle cases where an instruction is "after" another instruction but actually gets executed before it. They can just handle all instructions linearly, just like the CPU does at the time of execution.
Also the fact that no one has done it before (and it would be such an awesome feature for users) makes it something that *should* be done :D

**Comment by farmdve** [comment]
I won't pretend to know anything about MIPS, but here is a fix in the original QEMU source related to delay slots.

https://github.com/qemu/qemu/commit/a5f533909e746ca6e534b232fb42c9c6fd81b468

Is it related?
