### ISSUE TITLE
uc_modes for each supported cpu

### ISSUE THREAD

**Issue by ZakDanger** [unicorn-engine/unicorn#390]
The layout of uc_mode currently isn't as clear as it could be for the various supported cpus.
What do you think about checking it to something like:

// Mode type
typedef enum uc_mode {
    UC_MODE_LITTLE_ENDIAN = 0,  // little-endian mode (default mode)
    UC_MODE_BIG_ENDIAN = 1 << 30,   // big-endian mode
    // arm / arm64
    UC_MODE_ARM = 0,    // 32-bit ARM
    UC_MODE_THUMB = 1 << 4, // ARM's Thumb mode, including Thumb-2
    UC_MODE_MCLASS = 1 << 5,    // ARM's Cortex-M series
    UC_MODE_V8 = 1 << 6,    // ARMv8 A32 encodings for ARM
    // mips
    UC_MODE_MICRO = 1 << 4, // MicroMips mode (MIPS)
    UC_MODE_MIPS3 = 1 << 5, // Mips III ISA
    UC_MODE_MIPS32R6 = 1 << 6, // Mips32r6 ISA
    UC_MODE_MIPS32 = UC_MODE_32,    // Mips32 ISA (Mips)
    UC_MODE_MIPS64 = UC_MODE_64,    // Mips64 ISA (Mips)
    // x86 / x64
    UC_MODE_16 = 1 << 1,    // 16-bit mode (X86)
    UC_MODE_32 = 1 << 2,    // 32-bit mode (X86)
    UC_MODE_64 = 1 << 3,    // 64-bit mode (X86, PPC)
    // ppc
    UC_MODE_64 = 1 << 3,    // 64-bit mode (X86, PPC)
    UC_MODE_QPX = 1 << 4, // Quad Processing eXtensions mode (PPC)
    // sparc
    UC_MODE_V9 = 1 << 4, // SparcV9 mode (Sparc)
    // m68k
} uc_mode;

Another possibility include renaming the mode enums to contain the prefix of the CPU they are for, eg:
    // x86
    UC_MODE_X86_16 = 1 << 1,    // 16-bit mode (X86)
    UC_MODE_X86_32 = 1 << 2,    // 32-bit mode (X86)
    UC_MODE_X86_64 = 1 << 3,    // 64-bit mode (X86, PPC)
    // ppc
    UC_MODE_PPC_64 = 1 << 3,    // 64-bit mode (X86, PPC)

And yet another idea would be to have separate uc_mode enums for each cpu, eg:
typedef enum uc_mode_x86 {
    UC_MODE_16 = 1 << 1,    // 16-bit mode (X86)
    UC_MODE_32 = 1 << 2,    // 32-bit mode (X86)
    UC_MODE_64 = 1 << 3,    // 64-bit mode (X86, PPC)
} uc_mode_x86 ;

**Comment by aquynh** [comment]
- on the first idea, you just moved around the enums, without changing anything? this looks OK to me.

- on the 2nd idea, i think we dont gain much from renaming the modes. in return, we pay by breaking all the apps writing for current Unicorn version. we want to avoid the compatibility issue if possible.

- on the last idea: note that we have `uc_open()` declared like this:

        uc_err uc_open(uc_arch arch, uc_mode mode, uc_engine **uc);

  how do you fit `uc_mode_x86` into the prototype now?

**Comment by xorstream** [comment]
Yes just rearranged the enums in the first instance.
The idea for changing the names or type is that there are some cases where the same value is used for multiple cpus, like the value:
UC_MODE_64 = 1 << 3, // 64-bit mode (X86, PPC)

Perhaps instead we could add more aliases like:
UC_MODE_MIPS64 = UC_MODE_64, // Mips64 ISA (Mips)

Also another thing is that since not all flags apply to each CPU perhaps it would be better to start the set of flags for each cpu at like:
UC_MODE_1 = 1 << 0,
UC_MODE_2 = 1 << 1,

because otherwise we may soon run out of the 32 bit space available, especially as more CPUs get added and potentially more special cases are handled for each CPU.

**Comment by aquynh** [comment]
i think it is impossible to ever use up all the space for CPU modes (but that would mean Unicorn is super successful :-) )

the reason is that we can reuse the values of modes from other archs, because they are mutually exclusive. for example, we are having UC_MODE_V9 = UC_MODE_THUMB (for Sparc & ARM) without any conflicts. so when we add new architecture, we can start from (1 << 0), as you mentioned.

agreed that adding more aliases is OK if needed.
