### ISSUE TITLE
pkg-config missing --static

### ISSUE THREAD

**Issue by crowell** [unicorn-engine/unicorn#393]
```bash
$ pkg-config --static unicorn
$ pkg-config --libs unicorn   
-L/usr//lib -lunicorn
```

**Comment by radare** [comment]
Two options here:

* unicorn is not compiled for static and the pkgconfig file doesnt provides this
* the pkgconfig file is wrongly written

**Comment by crowell** [comment]
unicorn is certainly compile for static here, i have this file

```bash
$ file /usr/lib/libunicorn.a 
/usr/lib/libunicorn.a: current ar archive
```

**Comment by aquynh** [comment]
@radare, we also have the same issue with Casptone, right? 
`pkg-config --static capstone` returns nothing, even though i have `/usr/local/lib/libcapstone.a` on my machine.

**Comment by crowell** [comment]
Yep, same issue for capstone.  I just tested a static linked thing with unicorn manually providing the flags and it worked, so making a static thing for pkg config should fly

**Comment by radare** [comment]
Yep

**Comment by aquynh** [comment]
@crowell, is using only "--static" a correct way for pkg-config? i think it needs option "--libs" as well.

```
$ pkg-config --libs unicorn
-lunicorn  

$ pkg-config --libs --static unicorn
-lunicorn  
```

**Comment by radare** [comment]
If you read the manpage, --static in pkg-config means that it will supply all the dependency libraries required to build unicorn statically. It have nothing to do with providing a path to the static library, because it asumes the project has been already compiled statically. This is part of the GNU crap, so i guess there's nothing to fix here. And yes. it needs to be exeuted with --libs to get some output.

If you want to keep some sanity dont even try to read pkg-config source code. which is >20KLOC, when it can be resplaced in few lines of shellscript

**Comment by radare** [comment]
And the `.pc` have no way to specify the path to the statically linked library, it will require to have a separate pc file named `unicorn-static.pc` or so to get this done

**Comment by aquynh** [comment]
Close, thanks

**Comment by crazybytes** [comment]
fuck it

**Comment by crazybytes** [comment]
The illuminati fucks everything up. All forums are full of trolls.
