### ISSUE TITLE
uc_cpu_dump_state()

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#459]
Got a uc_cpu_dump_state() function added to uc.c.

Worthy of a PR?

**Comment by aquynh** [comment]
i am not sure how this adds anything new. can you post the output of this API?

**Comment by aquynh** [comment]
there are other approaches so that we dont need to add a new API:

- add a new query option, for example UC_QUERY_X86_XXX for a specific info you want to get.
- add a new query option such as UC_QUERY_CPU_STATE to return all the internal info. this requires to define new structures for internal CPU states of all architectures.

this returns a struct of info, and this is more flexible that just print out all of them to the console.

**Comment by egberts** [comment]
Sounds good.  Staying focused on #364 and #379 myself...

**Comment by egberts** [comment]
Closing....

**Comment by aquynh** [comment]
This is interesting, why did you close it?
