### ISSUE TITLE
hook_count_cb doesn't stop at n instructions

### ISSUE THREAD

**Issue by egberts** [unicorn-engine/unicorn#465]
When passing count to `uc_emu_start`, it doesn't stop at the desired nth instruction, particularly if the uc->emu_count is less than approximately 6 opcode instruction sets.

Pseudo C programming is:

``` c
total_instructions = 0;
void test_code_hook()
{
    ++total_instructions;
}
...

  uc_open(UC_ARCH_X86, UC_MODE_32, &uc);
  uc_hook_add(uc, &trace1, UC_HOOK_CODE, test_code_hook, NULL, 1, 0);
  uc_mem_map(uc, address, 2 * 1024 * 1024, UC_PROT_ALL);

  expected_instructions = 2;
  uc_mem_write(uc, address, code, expected_instructions);
  uc_emu_start(uc, address, address + expected_instructions, 0, expected_instructions);

  // Should be equal, but it's not.
  assert_int_equal(expected_instructions, total_instructions);
```

**Comment by aquynh** [comment]
would you please put a testcase under tests/ for easier confirmation & test bugfix?

**Comment by aquynh** [comment]
your testcase is wrong, because it confuses global & local variables (using the same name). i fixed that, and it passes all the tests now: https://github.com/unicorn-engine/unicorn/commit/ad6bb8c9f8f710fefe35c0d7bc9556e68b184714

so nothing is wrong with instruction counting of uc_emu_start(). thanks.

**Comment by danghvu** [comment]
if this is still an issue please reopen it.
