### ISSUE TITLE
have some question about arm mode and memory problem

### ISSUE THREAD

**Issue by fr0zenrain** [unicorn-engine/unicorn#519]
1.unicorn can support arm and thumb auto switch,just need set mode in first initialize.
2. i load an arm dynamic library into host memory,and this binary function address are fixed 
   now i  want to emulator this library, obviously i can't copy the memory to emulator ,it have other method to resolve it? thanks

**Comment by sashs** [comment]
How do you mean this "obviously i can't copy the memory to emulator"? Are you trying to execute the code which is located in the host memory?

**Comment by fr0zenrain** [comment]
thanks,i mean i allocate memory before, uc_mem_map after,and i copy my memory to unicorn's memory, i think not ok,and i test not ok. why i must allocated before,because i loaded an executable.

**Comment by fr0zenrain** [comment]
just direct emulate host memory instruction

**Comment by aquynh** [comment]
Can you post your code?

**Comment by sh1ftchg** [comment]
"it have other method to resolve it?" Yeah, read the documentation -  you are looking for "uc_mem_map_ptr".

If you used a system loader to "load an executable" the binary will have been loaded and mapped into memory with the page aligned requested protections: code typically has x (executable) data varies, some with r (read), others with w (write) or c (copy on write, typically for thread safety). Therefore, you will need to change the protection of the VADs to allow rw (virtual address descriptors in accordance with your architectures MMU - most systems provide an independent API to do this: ie. on Windows you can accomplish this via VirtualProtect). You should probably go ahead and drop c while you're at it - this version of QEMU is not multi threaded (unicorn simply exposes QEMU's already existent functionality in a far more user friendly API... It doesn't add/change anything of value to QEMU, it does add memory leaks and unnecessary data abstraction at the cost of memory and negligible extra cycles for its own internal convenience so if you're planning full executable emulation - you should just learn to use QEMU{for multi threading you need KVM integration}). Ultimately, every OS loads a binary differently, and even then - differently based on version (see Android) so for what you're asking - there is no one size fits all fix.

Alternatively, the easiest route imo because you can stuck to unicorn, is to use load/link the targeted system's loader - personally I load a copy of "ld.so" - link it to stubs which provide the necessities (filtered file access and memory management {important! link to qemu's qmalloc/qfree per QEMU's reqs}, tack in some core utils like tiny lib c etc via hooks to translate arguments from the emulated architecture to the native). Emulate a call to load/execute the binary and viola! If you did everything correctly you can now load a binary precisely the way system does with the benefit of having the emulator link things to actual host implementations giving you fantastic speeds and letting you focus on the emulated/instrumented data. The main benefit here is it's as close to a one size fits all solution as you can get.

Also, be weary of loading an external binary - even if the main thread is not executed, often (especially on Winblows, but also in some ELF impls) the loader/linker executes a small stub of the binary to "fixup" - relocating code, loading and linking dependant binaries, generating function lookup tables, initializing contexts (such as thread/process local).

**Comment by aquynh** [comment]
thanks for a long explanation! btw, we fixed many memory leaking issues we knew, so check it out the latest Github code ;-)

**Comment by fr0zenrain** [comment]
thanks sh1ftchg & aquynh , now  i allocated virtual address space by myself, and i achieved VirtualAlloc  or mmap based uc_mem_map  , i use uc_mem_write to write binary to unicorn engine , i complete relocate binary use uc_mem_read,uc_mem_write finally , i can't operate the memory directly,i think it's not friendly. maybe i need a virtual address to physical address translate api ?
