### ISSUE TITLE
Support registering IO register read/write handlers

### ISSUE THREAD

**Issue by neobrain** [unicorn-engine/unicorn#565]
It seems to me that unicorn does not expose a way to expose "active" memory (i.e. MMIO), which triggers some sort of hardware action when being written to/read from. For instance, a game console emulator may want to recognize writes to a particular address as a rendering command to the console's GPU and then consequently trigger the GPU emulation code.

For best flexibility, I would propose unicorn to invoke a user-defined callback function whenever it encounters a read from/write to an unmapped address. Alternatively, the list of reads/writes invoking the callback function could be restricted to a previously defined list of IO registers.

I've been looking through the issue tracker and surprisingly found no existing requests for such a feature, even though I thought it would be fairly common use case in low-level emulation.

**Comment by lunixbochs** [comment]
Unicorn has a hook for "unmapped read".

**Comment by neobrain** [comment]
@lunixbochs I'm aware of the unmapped read/write hooks, but there are one small and one large problem with them, as far as I can see anyway:
* for writes, it's not clear to me what the `uc_cb_eventmem_t` documentation means with "continue"ing. Would it resume execution, skipping the current instruction? Or instead, would it re-execute the current instruction, expecting the previously unmapped address to be mapped now? In either case, how can I be sure the instruction operation has actually completed successfully (e.g. in the case of a stack push, which needs to modify the stack pointer after the memory access)?
* for reads, there is no simple way to actually return a value from the handler to unicorn (which of course would be necessary when the emulated application is reading an IO register value into a CPU register). I suppose you could stop emulation, map a new memory region, write the register value to the appropriate offset, then re-run unicorn for exactly one instruction, and then unmap that memory region, and finally resume emulation normally. That seems overly hacky, though.

**Comment by neobrain** [comment]
@chriscz I don't want to map static memory, though - emulating IO registers properly requires a custom handler to be installable on memory access (to be able to make emulated hardware devices react appropriately to a particular read/write).

**Comment by kitling** [comment]
@aquynh 

Is there any intention of implementing an API for this, or is there a (preferrably easy) way to do this in the state that unicorn is currently in?

(I'd like to implement GPIO and similar for my project.)

**Comment by aquynh** [comment]
Yes, can you post your proposal? If we all agree, then plz send pull req to
implement it, i will merge.

**Comment by kitling** [comment]
Warning: I don't design APIs, so this may be dirty.

I propose another callback type or two that is almost identical to uc_cb_insn_in_t and uc_cb_insn_out_t, basicly replace port with address.

```
typedef uint32_t (*uc_cb_active_read_t)(uc_engine *uc, uint32_t address, int size, void *user_data);

typedef void (*uc_cb_active_write_t)(uc_engine *uc, uint32_t port, int address, uint32_t value, void *user_data);
```
These would work exactly like uc_cb_insn_in_t and uc_cb_insn_out_t.

However, I feel that merging these two callback types would make sense, you can have a callback for each type of IO, not 2, for IO read and IO write. Therefore, I propose:

```
typedef void (*uc_cb_active_mem_t)(uc_engine *uc, uint32_t address, int size, uint32_t *value, void *user_data);
```
instead. For read, we would write the value into the value variable, for write, we would read it out.

This still leaves the problem of when to call these callbacks. We could call these on any read/write, on an unmapped/invalid read, or we could make a new type of memory region, so we can map IO, and call on read/write to those regions. Something like:
```
UC_PROT_IO = 8
```
And then you can give various read/write protections and define it as IO memory.

And now you can tell me how hacky this API would be. Go ahead. I'm just thinking out loud. And I am certainly open for suggestions.

**Comment by kitling** [comment]
Alternatively, keeping the same callback above, but don't register hooks.

A new API function, idk, `uc_mem_map_active` or `uc_mem_map_device`:

```
uc_err uc_mem_map_active(uc_engine *uc, uint64_t address, size_t size, uc_cb_active_mem_t callback, void *user_data);
```

The passed callback handles reads and writes to that region, user_data get's passed to the callback so that it can store data...

Shoot, I forgot a enum argument for the callback type, didn't I? Time to edit that...

**Comment by kitling** [comment]
Another alternative, we can redefine the semantics for the existing UC_HOOK_MEM_{READ,WRITE,FETCH}_UNMAPPED hooks. This modification could be as 'simple' as passing the `value` parameter by pointer instead of by value, like my earlier proposals involving uc_cb_active_mem_t.

This feels natural, but doesn't feel quite right to be only focusing this on unmapped read/write/fetch. Honestly, if this were to happen, I'd want to modify ALL callbacks involving memory, so we can allow the callback to arbitrarily modify the value before reading from/writing to memory. May or may not be useful for some people. (On the fly encryption/decryption into memory, but the emulated program just sees decrypted data?)

(Side note: Is the address being passed *really* the address of the code being executed? Or is it the address being read/written, and it's mislabled atm?)

**Comment by kitling** [comment]
So, taking a fresh look at this now that it's summertime, I can only really see a few ways to implement this properly:

 - New hook types, `UC_HOOK_MMIO_READ` and `UC_HOOK_MMIO_WRITE`. The issue there is that if you want a seperate hook for READ and WRITE, you need to call uc_hook_add twice -- meaning that you end up creating the memory area twice unless you check for it, find it, and modify it. I don't want to deal with that. I don't really think anyone wants to deal with that. Or you can add a vararg so that you can pass both callbacks at once, but that's inconsistant API.
 - New hook types, redux. What @aquynh appeared to be suggesting in reply to my PR is adding a new flag to `uc_mem_map`, and then adding hooks that become the callbacks for all MMIO? My issue with this is that having different callbacks for different IO areas is a nice thing to have, which this doesn't allow for. I would like some clarification, though. If this isn't what you meant, please let me know.
 - New API, such as a modified version of my previous `uc_mmio_map` PR. Honestly, I think this might be the best way to go, after fixing the memory leak and some parts of my old proposed API that I don't like. I may PR a new version of this later today.
 - Modification of old API. This would break stuff. Not a good choice.

**Comment by lunixbochs** [comment]
If you map the mmio memory, you can use the existing hooks (MEM_WRITE, MEM_READ_AFTER) to implement mmio.

**Comment by kitling** [comment]
Okay, so we can use existing hooks too. But once again, the issue is that you can't have different callbacks for different pages.

Though... I guess you could use the beginning and end parameters, as well as unicorn provided mmio callbacks to call the hooks. That doesn't actually seem too bad. Perhaps that's what @aquynh was referring to.

Such an API, as I'm envisioning it, would look like this, off the top of my head:
```
uc_mem_map(..., 0xFFFF1000, 0x1000, UC_PROT_ALL | UC_MMIO, ...)
uc_hook_add(..., 0xFFFF1000, 0xFFFF0100, UC_*_READ, read_cb, ...)
uc_hook_add(..., 0xFFFF1100, 0xFFFF0200, UC_*_READ, read_cb_100, ...)
```

I probably got the order of the arguments wrong, since I'm writing this from my phone. But you shpuld get the idea. Here comes another possible PR... but if someone gets to this before me, feel free.

**Comment by lunixbochs** [comment]
> different callbacks for different pages

That's what begin/end are for, so Unicorn can page filter for you.

**Comment by lunixbochs** [comment]
In this case you don't need a new API at all. The MMIO flag doesn't seem to mean anything.

Just uc_mem_map an area, then add hooks for MEM_READ_AFTER and MEM_WRITE on a range.

**Comment by kitling** [comment]
@lunixbochs The MMIO mapping flag would be to map an qemu IO page, instead of a regular page that is backed by RAM. It's not meant to be used without callbacks implementing read/write.

Yes, there are workarounds for the lack of support for IO pages using hooks, whether it be through unmapped page hooks, protected page hooks, or hooks for pages that are mapped normally, but unless you use unmapped pages, you are allocating RW memory to back the page, which is completely unnecesssary for memory whose behavior is managed by a set of callbacks.

And on top of that, support for IO memory is already there in qemu, it's just not exposed in unicorn. I see no reason not to expose it. Not exposing it is a design oversight. Yes, you can work around it, but it's not the best/proper solution.

The reason why I didn't initially look at begin and end and go "Ah, that's how to page filter!" is because I'd prefer to associate these callbacks with the IO page directly instead of dealing with a list of hooks to iterate through. The latter has more overhead at runtime. *That* is why I sought to implement a new function, `uc_mmio_map`. *That* is why I dismissed hooks initially. But if I have to use hooks to get something into unicorn that properly exposes MMIO? Fine.

**Comment by lunixbochs** [comment]
If you find hook iteration performance to be a major hit (I think you'll find it's a very small percentage of what softmmu itself takes, especially if you have <10 memory hooks), converting to a modified binary search is fairly easy and would mostly eliminate the overhead even for much larger numbers of hooks.

Okay, adding UC_MAP_MMIO is fine for not allocating a backing page, and stubbing read/write (so it must be handled by the hooks).

I'd support modifying the existing MEM_READ_AFTER and MEM_WRITE hooks as well to allow you to change the value as long as it's not super intrusive (for the next breaking Unicorn API change). Could rename them to HOOK_READ and HOOK_WRITE, move the current HOOK_READ to something like HOOK_PREREAD and keep the old HOOK_READ semantics. There's no getting around iterating over non-MMIO memory hooks for now, even for an MMIO page, so I think we should focus these improvements on the hook interface instead of adding new surface.

**Comment by kitling** [comment]
My current plan for the implementation with hooks is to iterate over the hooks and call a hook in the io callback... though it occurs to me that this may be difficult, since that callback is passed the address *relative to the start of the region it occurs in*. This is probably a reason that I forgot for why I didn't want to use hooks...

I mostly finished the new version of the old PR I did, with some modifications. It's #850. I don't expect it to get accepted, given the comments and general trend of discussion in this trend, but it's there. Next chance I get, I will start looking at using hooks to implement the same thing.

**Comment by aut0** [comment]
> My current plan for the implementation with hooks is to iterate over the hooks and call a hook in the io callback... though it occurs to me that this may be difficult, since that callback is passed the address _relative to the start of the region it occurs in_. This is probably a reason that I forgot for why I didn't want to use hooks...

I experimented with your PR #850 and it seems like when mmio_map a memory region the callback is also called with the offset passed as the address and not the global address where the read/write occured. Is it possible to get the global address in the callback?

**Comment by kitlith** [comment]
I don't think so, unless there's an option in a struct that I missed when implementing *or* we modify qemu to pass the global address... and hope that indeed, nothing else relies on qemu's behavior there.

A workaround would be... a wrapper around the final hook that takes an allocated 'userdata' structure that stores the base address, the hook we're delegating to, and the actual userdata structure, similar to the first PR, but then you have to figure out a place to put the deallocation code (which is easy, but if we can avoid the workaround in the first place then that's a plus)
