### ISSUE TITLE
bindings: registers are signed values

### ISSUE THREAD

**Issue by crowell** [unicorn-engine/unicorn#654]
```
In [1]: from unicorn import *

In [2]: from unicorn.x86_const import *

In [3]: mu = Uc(UC_ARCH_X86, UC_MODE_64)

In [4]: mu.reg_write(UC_X86_REG_RIP, 0xffffff8000200000)

In [5]: mu.reg_read(UC_X86_REG_RIP)
Out[5]: -549753716736
```

registers should be unsigned values. at least in python you're using ctypes for `int64`, instead of `uint64`

It doesn't make sense for `$pc` to ever be negative, especially when do things like map kernels there ;)

**Comment by aquynh** [comment]
Can you send a pull req for this?

**Comment by mrphrazer** [comment]
I think that also holds for the memory hooks?

```python

UC_HOOK_MEM_INVALID_CB = ctypes.CFUNCTYPE(
    ctypes.c_bool, uc_engine, ctypes.c_int,
    ctypes.c_uint64, ctypes.c_int, ctypes.c_int64, ctypes.c_void_p
)
UC_HOOK_MEM_ACCESS_CB = ctypes.CFUNCTYPE(
    None, uc_engine, ctypes.c_int,
    ctypes.c_uint64, ctypes.c_int, ctypes.c_int64, ctypes.c_void_p
```

**Comment by aquynh** [comment]
Pull req, please?

**Comment by lowlyw** [comment]
https://github.com/unicorn-engine/unicorn/pull/661

for fix for ruby impl

**Comment by aquynh** [comment]
@crowell: fixed now thanks to @mrphrazer. please report if you still have issues, thanks.

**Comment by mrphrazer** [comment]
we have the same problems in the hooks, `value` can be negative:

```python
    def _hook_mem_invalid_cb(self, handle, access, address, size, value, user_data):
        # call user's callback with self object
        (cb, data) = self._callbacks[user_data]
        return cb(self, access, address, size, value, data)

    def _hook_mem_access_cb(self, handle, access, address, size, value, user_data):
        # call user's callback with self object
        (cb, data) = self._callbacks[user_data]
        cb(self, access, address, size, value, data)
```
A possible fix is
```python
value &= 2 ** (size * 8) - 1
```

**Comment by aquynh** [comment]
i am not sure it is a good idea to do this conversion inside the framework, rather than doing it in your app. is this what everyone wants?

**Comment by sh1ftchg** [comment]
This is a good idea. Why? A processor could be executing in an 8, 16, 32, 64 or less commonly / more advanced 128, 256, 384, or 512 bit context. Most of the time the only defining property a processor makes for its registers is its bit-size and their positions. Therefore if you leave these as signed values in the API it forces an implicit signed extension and therefore no longer accurately represents the register. In fact none of it should be signed unless explicitly declared as such by the processor specification.

ie. A 32 bit processor is told to store the value `(char) 0xfe; // -2 or 0b11111110` which is what, -1 in decimal notation? (Sorry, doing this on my phone in my head.)  but when stored in the 32 bit register   slot declared as signed the binary value that actually gets stored after signed extension is `(int)  0xfffffffe; // -2 or 0b11111111_11111111_11111111_11111111`... Which no longer represents the actual bits or their positions... While you can argue this can be worked around, and it can, that can only be done with context awareness: I know it contains an 8 bit signed value therefore it must be the char's representation. Not sure if there's a way without the context of the instructions or code which altered it.

Essentially, what I'm saying is [b]the only true way to represent a register anywhere is with an unsigned value[/b] since only that guarantees the last bit is a part of the actual value and not the result of signed extension or integer overflow.

**Comment by mrphrazer** [comment]
@aquynh I do see your point; I do not know either. However, I think there should be some consistency between `reg_read`, `reg_write` and the callbacks. If the register reads/writes return an unsigned value while the memory hooks operate on signed values it might be confusing.

**Comment by lowlyw** [comment]
This is still the case in Haskell bindings. I'm not a Haskell programmer so I'm not even going to pretend to know how to get it building and testing

**Comment by lowlyw** [comment]
Also what is the consensus on the memory access use for these, they're broken still afaik for most of the bindings
