### ISSUE TITLE
GO binding in MODE_THUMB (Invalid memory fetch (UC_ERR_FETCH_UNMAPPED))

### ISSUE THREAD

**Issue by LaChancla0** [unicorn-engine/unicorn#665]
I'm trying to test this simple go program

```
mu, _ := uc.NewUnicorn(uc.ARCH_ARM, uc.MODE_THUMB)
code := []byte{0x81, 0xb0} //SUB SP, #0x4
mu.MemMap(0x1000, 2 * 1024 * 1024)
mu.MemWrite(0x1000, code)
mu.RegWrite(uc.ARM_REG_SP, 0x1234)

if err := mu.Start(0x1000, 0x1000+uint64(len(code))); err != nil {
         fmt.Errorf("Start error: %v", err)
}
```

but I get this error upon executing the mu.Start

> Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)

pretty sure the area is not unmapped (0x1000)

**Comment by sh1ftchg** [comment]
For future reference: To align arbitrary address ranges dynamically use the following pseudo code converted to the desired language bindings of your choice:

ALIGN = 0x1000
MASK = ~(ALIGN - 1)
start = address_start & MASK # bitwise floor to the alignment boundary
end = (address_end + ALIGN) & MASK # bitwise ceil boundary aligned

Secondly, and likely the cause of your problem: ignore mode. In my.Start -> use the address 0x1001 as the start address. Setting thumb mode in the uc structure initialization is no longer useful: the ARM processor automatically uses the first bit of PC to select ARM or THUMB execution. (1 equals thumb, 0 = arm) This works because THUMB is a minimum of 2 bytes per instruction and ARM is 4; thus the first bit is rather useless. Hence per specification it is used to change processor instruction states.

**Comment by LaChancla0** [comment]
Thanks for
