### ISSUE TITLE
Negative Offset for FS: segment register failing

### ISSUE THREAD

**Issue by Thiefyface** [unicorn-engine/unicorn#718]
It seems that negative offsets from segment registers end up accessing the 
absolute value of the offset given, and not the negative offset.
 ```
# example:
mov fs:[0xfffffffffffffff8], 0x10 => mov [0xfffffffffffffff8], 0x10).
```
__Error when emulating code:__
 ```
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)
 ```
__Instructions at time of crash:__
 ```
0x7f07777e3d2d: sub rsp, 0x538   \x48\x81\xec\x38\x05\x00\x00
0x7f07777e3d34: mov rax, qword ptr [rip + 0x35113d]   \x48\x8b\x05\x3d\x11\x35\x00
0x7f07777e3d3b: mov eax, dword ptr fs:[rax]   \x64\x8b\x00   <- Crash here
 ```
__Registers at time of crash:__
 ```
gs : 0x1800
rip : 0x7f07777e3d3b
rdx : 0x7ffcd39adf28
fs : 0x800
cs : 0x33
es : 0x0
r13 : 0x7ffcd39ae100
rcx : 0xffffffffffffff98
rax : 0xffffffffffffff98
r14 : 0x0
r15 : 0x0
r12 : 0x400440
rsi : 0x400604
r10 : 0x64
r11 : 0x346
rsp : 0x7ffcd39ad9b0
ds : 0x0
rbx : 0x0
ss : 0x2b
r8 : 0x1
r9 : 0x13
rbp : 0x7ffcd39adf10
eflags : 0x202
rdi : 0x7f0777b36600
 ```

__Parameters from UC_HOOK_MEM_INVALID:__
 ```
address 0xffffffffffffff98
size 0x4
access 0x13
value 0x0
 ```

__Temporary Workaround:__

The following was what I was using to get around FS: and GS: issues, with the last line needing to be uncommented in order to fix the issue. After the last line is uncommented, the program was emulating sucessfully.

 ```
        self.uni.mem_map(0x0,0x1000,3)
        self.uni.mem_map(0x1000,0x1000,3)
        self.uni.reg_write(uni_dict["fs"],0x800)
        self.uni.reg_write(uni_dict["gs"],0x1800)
        # hack needed for negative offset to fs...
        #self.uni.mem_map(0xfffffffffffff000,0x1000,3)
 ```

**Comment by cseagle** [comment]
Sorry, I'm on mobile atm, but x86_64 uses MSRs to specify the base of the
fs and gs segments. I don't recall how unicorn supports writing to MSRs but
that might be necessary.

If we assume in your example that fs base is zero, then the expected memory
access goes to [0 + rax] == [0+ 0xffffffffffffff98] which seems to have
been correctly computed by unicorn.

If the code you are emulating uses negative offsets from fs it seems it
would be necessary to map the required region just below fs base just as
you have done. From the CPUs perspective offsets are considered unsigned.

My question to you is what address do you think should have been accessed
at the faulting instruction?

Chris

On Jan 14, 2017 5:12 PM, "Lilith Wyatt" <notifications@github.com> wrote:

It seems that negative offsets from segment registers end up accessing the
absolute value of the offset given, and not the negative offset.

# example:
mov fs:[0xfffffffffffffff8], 0x10 => mov [0xfffffffffffffff8], 0x10).

*Error when emulating code:*

unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)

*Instructions at time of crash:*

0x7f07777e3d2d: sub rsp, 0x538   \x48\x81\xec\x38\x05\x00\x00
0x7f07777e3d34: mov rax, qword ptr [rip + 0x35113d]
\x48\x8b\x05\x3d\x11\x35\x00
0x7f07777e3d3b: mov eax, dword ptr fs:[rax]   \x64\x8b\x00   <- Crash here

*Registers at time of crash:*

gs : 0x1800
rip : 0x7f07777e3d3b
rdx : 0x7ffcd39adf28
fs : 0x800
cs : 0x33
es : 0x0
r13 : 0x7ffcd39ae100
rcx : 0xffffffffffffff98
rax : 0xffffffffffffff98
r14 : 0x0
r15 : 0x0
r12 : 0x400440
rsi : 0x400604
r10 : 0x64
r11 : 0x346
rsp : 0x7ffcd39ad9b0
ds : 0x0
rbx : 0x0
ss : 0x2b
r8 : 0x1
r9 : 0x13
rbp : 0x7ffcd39adf10
eflags : 0x202
rdi : 0x7f0777b36600

*Parameters from UC_HOOK_MEM_INVALID:*

address 0xffffffffffffff98
size 0x4
access 0x13
value 0x0

The following was what I was using to get around FS: and GS: issues, with
the last line needing to be uncommented in order to fix the issue.

       self.uni.mem_map(0x0,0x1000,3)
       self.uni.mem_map(0x1000,0x1000,3)
       self.uni.reg_write(uni_dict["fs"],0x800)
       self.uni.reg_write(uni_dict["gs"],0x1800)
       # hack needed for negative offset to fs...
       #self.uni.mem_map(0xfffffffffffff000,0x1000,3)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/unicorn-engine/unicorn/issues/718>, or mute the thread

**Comment by Thiefyface** [comment]
For the situation that I previously listed:
```
$rip ==  mov eax, dword ptr fs:[rax]
$rax == 0xffffffffffffff98
$fs == 0x800
```
I was expecting that `mov eax, dword ptr fs:[rax]` would be equivalent to `mov eax, [0x800 + 0xffffffffffffff98]`. If my understanding is correct, this would have overflowed and wrapped around into the valid address space that I had mapped before. 

This did not occur though, since the CPU ignored the value of $fs and accessed 0xffffffffffffff98, an unmapped memory address, as shown by the parameters of the UC_HOOK_MEM_INVALID hook callback.

If my understanding of this situation is incorrect, please let me know (this is the first day I've really programmed with Unicorn Engine), thanks!

**Comment by lunixbochs** [comment]
You should use WRMSR to write the FS_base and GS_base MSRs instead of setting FS as a normal register. Additionally Unicorn should probably get support for these MSRs in the register read/write code. FS is a segment selector which isn't really useful on 64-bit.

**Comment by cseagle** [comment]
The only case in which fs contributes directly into an address computation is in 16-bit mode.

In 32-bit mode, fs holds an index into a descriptor table from which the base of the fs segment is retrieved, and to which your offset is added. So, in 32-bit mode you would need to ensure that an appropriate descriptor had been initialized and that fs held the index of that descriptor.

In 64-bit mode, quoting from the intel manuals:

"The hidden descriptor register fields for FS.base and GS.base are physically mapped to MSRs in order to load all
address bits supported by a 64-bit implementation. Software with CPL = 0 (privileged software) can load all
supported linear-address bits into FS.base or GS.base using WRMSR. Addresses written into the 64-bit FS.base
and GS.base registers must be in canonical form. A WRMSR instruction that attempts to write a non-canonical
address to those registers causes a #GP fault."

As Ryan mentioned, WRMSR should be used in your case. For fs, this is MSR 0xc0000100. WRFSBASE is also available if CR4.FSGSBASE[bit 16] == 1. Unicorn doesn't have an interface to let you set MSRs directly, so you'll need to emulate the instruction ahead of any other code you plan to emulate.

**Comment by Thiefyface** [comment]
Thank you very much for all the information/clarification, I guess I did have a fundamental misunderstanding. I'm going to close the issue, but as previously mentioned I do think that it would be a good addition to Unicorn if there was MSR functionality added. 

Cheers.
