### ISSUE TITLE
Remove all calls to exit()

### ISSUE THREAD

**Issue by radare** [unicorn-engine/unicorn#756]
Calling exit is a very bad practice and even more if used in libraries. The library should provide a way to recover from errors instead of killing the whole host application.

```
$ git grep 'exit(.);' qemu |wc -l
      11
```

**Comment by radare** [comment]
The same goes for assert and abort:

* [ ] 160 aborts
* [ ] 373 asserts

**Comment by lunixbochs** [comment]
The exits are here:

```
qemu/exec.c:                    exit(1);
qemu/glib_compat.c:   if (res == NULL) exit(1);
qemu/glib_compat.c:   if (res == NULL) exit(1);
qemu/glib_compat.c:   if (res == NULL) exit(1);
qemu/target-mips/helper.c:        exit(1);
qemu/tcg/ppc/tcg-target.c:        exit(1);
qemu/tcg/ppc/tcg-target.c:        exit(1);
qemu/tcg/ppc/tcg-target.c:        exit(1);
qemu/tcg/tcg.c:                            exit(1);
qemu/translate-all.c:        exit(1);
qemu/util/qemu-timer-common.c:        exit(1);
```

1. qemu_ram_remap(), looks like dead code
2. g_malloc(), g_malloc0, g_realloc() - I guess these should propagate out to a host memory error, but aren't worst case because your program is already going down if malloc fails.
3. mips_cpu_do_interrupt() on invalid exception (this should just return a uc error from emu_start)
4. `tcg_cache_init` when getauxval fails for some reason to get the cache sizes (this shouldn't exit at all, that's insane)
5. `tcg_add_target_add_op_defs` which I think runs on tcg init and is more a developer debug thing.
6. in `code_gen_alloc` if the code gen buffer fails to allocate.
7. If timer init fails on win32 (when unicorn is imported).
