### ISSUE TITLE
Inconsistent values of XMM and YMM registers

### ISSUE THREAD

**Issue by saelo** [unicorn-engine/unicorn#818]
The lower 128 bits of a YMM register are shared with the corresponding XMM register. As such, writing to e.g. XMM0 should reflect in YMM0. The following script tests this.
```
#!/usr/bin/python

from __future__ import print_function
from unicorn import *
from unicorn.x86_const import *

CODE = (b"\xF3\x0F\x2A\xC0"      # cvtsi2ss    xmm0, eax
        b"\x66\x0F\x7E\xC0")     # movd    eax, xmm0

ADDRESS = 0x1000000

try:
    mu = Uc(UC_ARCH_X86, UC_MODE_64)
    mu.mem_map(ADDRESS, 2 * 1024 * 1024)
    mu.mem_write(ADDRESS, CODE)
    mu.reg_write(UC_X86_REG_RAX, 0x122)
    mu.emu_start(ADDRESS, ADDRESS + len(CODE))

    print(">>> RAX = 0x%x" % mu.reg_read(UC_X86_REG_RAX))
    print(">>> XMM0 = 0x%x" % mu.reg_read(UC_X86_REG_XMM0))
    print(">>> YMM0 = 0x%x" % mu.reg_read(UC_X86_REG_YMM0))

except UcError as e:
    print("ERROR: %s" % e)
```

However, running this code yields incorrect results:
```
>>> RAX = 0x43910000
>>> XMM0 = 0x43910000
>>> YMM0 = 0x0
```

**Comment by aquynh** [comment]
the reason is that we havent supported read/write to these registers yet, hence you see 0 value returned.

you can add the missing registers to https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-i386/unicorn.c#L206 & https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-i386/unicorn.c#L745, then send in pull req to fix this issue.

**Comment by saelo** [comment]
Done: https://github.com/unicorn-engine/unicorn/pull/819
