### ISSUE TITLE
ARM emulation of interrupts

### ISSUE THREAD

**Issue by ghost** [unicorn-engine/unicorn#825]
Hi, I'm working on writing an ARM-based processor emulation using Unicorn.

How do I simulate generation of an interrupt (not an SVC)?

**Comment by lunixbochs** [comment]
Parse the interrupt vector table, set up any register state manually, jump to the right interrupt.

**Comment by markyi370** [comment]
@lunixbochs So there is no way to automatically handle this like a traditional ARM processor? I have to write this code manually?

**Comment by markyi370** [comment]
No updates? I really need this feature if I'm going to use Unicorn for my project.

**Comment by cseagle** [comment]
Unicorn is an instruction set emulator not a hardware emulator. The only
way to handle interrupts is from the software side of things as @lunixbochs
has described

On May 9, 2017 4:05 AM, "Mark Yisri" <notifications@github.com> wrote:

@lunixbochs <https://github.com/lunixbochs> So there is no way to
automatically handle this like a traditional ARM processor? I have to write
this code manually?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/unicorn-engine/unicorn/issues/825#issuecomment-300131552>,
or mute the thread

**Comment by lunixbochs** [comment]
Someone will likely need to port https://github.com/qemu/qemu/blob/stable-2.2/target-arm/helper.c#L3961 back into Unicorn and expose it somehow.

You (or someone else) can also port that function to use the Unicorn API, which should be pretty straightforward.
CPSR is already supported with reg_read/write, but someone should add reg_read(VBAR) support (to support a changed vector base address).

**Comment by markyi370** [comment]
> Unicorn is an instruction set emulator not a hardware emulator. The only
way to handle interrupts is from the software side of things as @lunixbochs
has described

The instruction set provides things like `IRET` for handling interrupts. While I understand hardware support is not the point of the project, I think a framework for interrupts should be provided at the very minimum.

**Comment by markyi370** [comment]
@lunixbochs I will have to check that out.

For a real piece of hardware, would the CPSR change modes?
