### ISSUE TITLE
Is the static library necessary for the python bindings?

### ISSUE THREAD

**Issue by bennofs** [unicorn-engine/unicorn#869]
The python bindings install both a shared library (`.so`) and a static library (`.a`) for `libunicorn` on my system. Is that necessary? It seems to me that the dynamic one would be enough, what is the static one used for?

**Comment by aquynh** [comment]
no it is not. but @rhelmot wanted the static lib there for other purposes.

**Comment by rhelmot** [comment]
I currently have an [application](https://github.com/angr/angr) that depends on this. I forget the extent to which we depend on the static library as opposed to the dynamic library, but I really don't want to find out. 

And I authored the Python packaging system and am in charge of Python distribution, so that's another factor.

**Comment by blshkv** [comment]
Guys, can you fix python bindings so that they could find a system library? Currently, it installs a second "unicorn/lib" directory and this seems unnecessary. This bug breaks our build system as well , see : https://github.com/pentoo/pentoo-overlay/pull/241

**Comment by rhelmot** [comment]
The presence of a lib directory is necessary for the dynamic library, which is absolutely critical for the functioning of the application, unless you're interested in rewriting the application.

**Comment by bennofs** [comment]
@rhelmot not necessarily. If you have installed `unicorn` system-wide via separate means, it should also work (i think it searches in `/usr/lib` as well as `/usr/local/lib` by default). Of course, it is then your responsibility to ensure that the versions match. Perhaps an option to use a system-provided `libunicorn` for the `setup.py` script would work? (Ideally, this option should also allow to override the hardcoded locations that the bindings search for the lib)

**Comment by rhelmot** [comment]
So this was the way capstone worked for a very long time - you had to install the native library through apt or some other package manager, otherwise the Python bindings won't work. The result was that it became a nightmare to manage versioning and builds in a system that is designed to deal exclusively with Python packages, plus every other issue that was submitted to my project which depends on capstone was something along the lines of "won't import because capstone won't import". 

So it's very critical that the default install build and bundle its own native library. I agree an option to disable this would be cool, but I don't know how to do this in setuptools or pip...

**Comment by blshkv** [comment]
Can you use the usual soname?
https://gist.github.com/lebedov/5111696

**Comment by blshkv** [comment]
If not, how about swig?
http://book.pythontips.com/en/latest/python_c_extension.html

**Comment by aquynh** [comment]
we did not want swig, but a simple clean lightweight binding.
-- 
Thanks,
Quynh

http://www.keystone-engine.org
http://www.capstone-engine.org
http://www.unicorn-engine.org

**Comment by blshkv** [comment]
Well, regardless. Could you please make an option for these who know what they are doing?
We can enforce whatever is required using portage system. I have hacked the setup.py file for now and cut the check away.

**Comment by bennofs** [comment]
@rhelmot one solution would be using an environment variable such as `UNICORN_NATIVE_PATH=/path/to/directory/with/libunicorn.so`

**Comment by rhelmot** [comment]
@blshkv I still don't understand what's wrong with the current build system. The idea of installing non-python data alongside the python bindings is an extremely common scenario, there's an entire flag to setuptools to `include_package_data`, which just copies any non-python data present in the package directories to wherever it's installed. We use the `build` step of the python build process to build the native libraries and copy them to this folder, and then they are copied by python to the installation site.

"Installing a second unicorn/lib" directory seems like an extremely silly grievance. We have done everything necessary to make the presence of this requirement known to the python build system. Does your package manager not use setuptools for installation?

With regards to the soname issue, the build of libunicorn on my machine produces a file with the soname `libunicorn.so.1`, which is "the usual soname" by my understanding. The file is named `libunicorn.so` at the request of @aquynh - I initially did have it named `libunicorn.so.1` but was asked to change it.

Also, this was the wrong issue to comment on in the first place. The original issue was about the necessity of bundling the _static_ library alongside the dynamic library, which is indeed questionably necessary. I only bring this up because I notice that this is something you care about, since https://github.com/pentoo/pentoo-overlay/issues/238 was linked to this issue somehow.

Sorry for being snippy, but you are barging into a very large and complicated project where a large amount of effort has already been put in to try to Do The Right Thing and demanding that large, invasive changes be made to compensate for a system which doesn't seem to be able to use the very common interface that we've set up to make things work.

@bennofs I do like the idea of using an environment variable, though if the path pointed to somewhere outside the typical library load path, it would need to be set every time you launched the python interpreter. This was the approach used by z3 for their python bindings, though I found it intolerable and ended up porting their build system to use the current approach as well, which they gladly accepted. If this is an acceptable solution to @blshkv I will implement it.

**Comment by bennofs** [comment]
@rhelmot i am not sure, does setuptools support some kind of configuration-at-install-time that can be accessed at runtime? Like a generated config.py or something? Then the path that was supplied by the user at install time could be used as a first try at runtime for loading. It would also ensure that none of the other hardcoded paths override it.

**Comment by rhelmot** [comment]
@bennofs we could absolutely just manually generate a config.py, but I don't think that's necessary - there's already a [large set of fallbacks](https://github.com/unicorn-engine/unicorn/blob/master/bindings/python/unicorn/unicorn.py#L73) we use to try to locate the dynamic library.

The more I read over this thread the more I think that the solution is just an environment variable to disable python building and installing the native library, to be able to play nice with a global install.

**Comment by blshkv** [comment]
@rhelmot yep, any option including an environment variable will do it.

**Comment by blshkv** [comment]
P.S. I have not looked at other bindings (go, ruby, java, etc). Please apply the same solution if it has the same design.

Having both libraries (shared and static) for each binding is definitely "silly" regardless how "large and complicated project" is. In fact, it might complicate all things instead.

Also, see FHS standard.

**Comment by rhelmot** [comment]
FHS standard applies when we're not using virtual environments constantly.

I already justified the use case for keeping the static library, and acknowledged that it could be removed given a little bit of refactoring on my part.

**Comment by blshkv** [comment]
FYI, you can also detect a presence of shared library using ```pkg-config``` from a makefile.
It can even detect a version of it:
```
pkg-config --modversion unicorn
1.0.1
```

**Comment by rhelmot** [comment]
That is very cool.

Proposed solution:

- in `setup.py`, shell out to `pkg-config` if installing on linux and ask for the current installed version of libunicorn
- if the current installed version is the same as the version in the bindings, skip the build step since it is not necessary.

@aquynh do you approve?

**Comment by aquynh** [comment]
what if pkgconfig is unavailable?
-- 
Thanks,
Quynh

http://www.keystone-engine.org
http://www.capstone-engine.org
http://www.unicorn-engine.org

**Comment by blshkv** [comment]
add it to requirement list, there is a python interface as well:
https://pypi.python.org/pypi/pkgconfig/

**Comment by aquynh** [comment]
@rhelmot, yes that is a reasonable solution, but if pkgconfig is unavailable, we fall back to do what we are doing (ie keep the current behaviour).

**Comment by blshkv** [comment]
Hi guys, I've looked through the changes and could not find any pkg-config call.
Can you confirm that the newly introduced variable ```LIBUNICORN_PATH``` will be detected automatically?

**Comment by rhelmot** [comment]
as mentioned [in the pull request](https://github.com/unicorn-engine/unicorn/pull/897) I realized that using pkg-config would make it awkward for package distributors to build during distribution.

I tested the changes with LIBUNICORN_PATH and confirmed that a) it inhibits the build and b) allows the python library to discover the library.

**Comment by blshkv** [comment]
I think you took a wrong approach. Instead of detecting the path, why don't you detect the system library (including the required version) and add ````-lmylib``` to compiler's options?

This is how would you help package distributors really. See the following document for details of the problem:
https://wiki.gentoo.org/wiki/Pkg-config

Also, a well written specs for it:
http://dev.gentoo.org/~mgorny/pkg-config-spec.html

**Comment by rhelmot** [comment]
I think you're misunderstanding the problem - the python bindings have no "python-specific" build related to them, they are simply unable to function without the dynamic library. The contents of the environment variable are actually totally unused at python installation time - you could just set `LIBUNICORN_PATH=1` during install and leave the variable unset during usage and it'll use the default system install.

If you think this is confusing I will change it.

**Comment by blshkv** [comment]
ok, I will try to pull the latest version and see if it works. Thanks!
