### ISSUE TITLE
X86_16: retf bug if UC_HOOK_MEM_READ used

### ISSUE THREAD

**Issue by mf85** [unicorn-engine/unicorn#966]
Instruction retf jumps to an invalid address if UC_HOOK_MEM_READ hook is added.
I also noticed that cs and ip are not in sync meaning (cs << 4) + ip != address

Example code.
[main.zip](https://github.com/unicorn-engine/unicorn/files/2035921/main.zip)

**Comment by AntiBlueQuirk** [comment]
I can confirm this issue. I stumbled upon it accidentally when I noticed weird behavior with retf not updating the ip to the expected value. Disabling my UC_HOOK_MEM_READ fixes the issue.

**Comment by AntiBlueQuirk** [comment]
I believe it has something to do with this line in [`translate.c:gen_op_ld_v`](https://github.com/unicorn-engine/unicorn/blob/4a86318cf45b7f0b8e01748ce700de1b7688d1e3/qemu/target-i386/translate.c#L586). On a hunch, I disabled this code, and the problem no longer occurs. I don't know the ramifications of this, but according to the comments, it has something to do with syncing the EIP.

If I had to guess, this line is modifying the EIP to have it synchronized properly during the memory read hook, but because the RETF is happening around the same time, it ends up corrupting the state. I don't know the internals of Unicorn/QEMU enough to know what the real solution is.

`gen_op_st_v`, a few lines later, is structured similarly, so I'm wondering if it's affected by a similar bug. Having a UC_HOOK_MEM_WRITE doesn't seem to cause any problems though.

The comment at [7053](https://github.com/unicorn-engine/unicorn/blob/4a86318cf45b7f0b8e01748ce700de1b7688d1e3/qemu/target-i386/translate.c#L7053) is interesting, since it mentions the EIP being updated, and this is where `gen_op_ld_v` is called for RETF instructions.

**Comment by macmade** [comment]
I'm having the same issue, and I can confirm that disabling `UC_HOOK_MEM_READ` fixes it.

My emulated code involving `retf` is:

    push 0x50
    push 0x00
    retf

So `retf` should jump to `0x50:00`, aka `0x500`.  
At this moment, `CS` is `0x00` and `IP` is `0x7DED `.

After `retf`, `CS` is `0x50`, which is right, but `IP` is `0x82ED`.

**Surprisingly, `IP` has been increased by `0x500`.**  
**I don't think this is a coincidence.**

I hope this will help figuring out what's wrong.

**Comment by macmade** [comment]
Maybe related: https://github.com/unicorn-engine/unicorn/issues/1114
